### DISCUSSION TITLE
ignition/butane and disk labels on OpenStack

### DISCUSSION THREAD

**Discussion by till** [flatcar/Flatcar#1057] [Q&A]
Hey, 

I am finally trying to update to butane and rebuild my configurations.

My environment: OpenStack
Flatcar: 3510.2.2

The butane itself is still pretty simple (there is more, but I have tested it in isolation):

```yaml
variant: flatcar
version: 1.0.0
storage:
  filesystems:
    - path: /customer
      device: /dev/sdb
      format: ext4
      label: CUSTOMER
      wipe_filesystem: true
      with_mount_unit: true
```

A similar ignition configuration was working before as the order of devices was actually predictable on instance creation. So, I was able to use `/dev/sdb` to format and label the device on boot. After that, I mounted it predictably by its label every time I rebooted the VM.

From my testing so far, `/dev/sdb` happens to be the root volume now. Always. No matter how often I try. Consistently.

So this does no longer work. In a nutshell, I get dropped into shell since ignition fails.

I looked a bit into how this is working on OpenStack and I seem to be unable to match the device by anything on first boot. I looked at all the `/dev/disk/by-*` paths, but nothing _exactly_ matches.

The only thing that could work maybe work is `/dev/disk/by-id/`:

```sh
lrwxrwxrwx.  1 root root   9 Jun  2 11:02 scsi-0QEMU_QEMU_HARDDISK_42b0eb4d-3b91-4b46-8 -> ../../sdb
```

The volume attached to the VM is `42b0eb4d-3b91-4b46-848c-b1bf95a4cd62`. So it seems like the hard-disk is truncated. But I can't find much as to how I would truncate the ID exactly to always work.

The docs are somewhat opaque here and leave out this detail. And the above seems to be a somewhat obscure way to do the mounting though it seems that even [the cloud controller relies on it](https://github.com/kubernetes/cloud-provider-openstack/pull/853/files). I was hoping I missed something obvious.

If not, then I guess that should be added to the docs as an example?

As I am walking through it all, I might send a PR for OpenStack related setup.
