### DISCUSSION TITLE
How to deal with permissions for USB devices

### DISCUSSION THREAD

**Discussion by ddt3** [flatcar/Flatcar#1616] [Q&A] [answered]
I am running a docker in flatcar (on proxmox) that uses a zigbee USB device. User running docker is `core`
```
$ lsusb
Bus 001 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 002: ID 1a86:55d4 QinHeng Electronics SONOFF Zigbee 3.0 USB Dongle Plus V2
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub

$ ls -al /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20231008154809-if00 
lrwxrwxrwx. 1 root root 13 Jan 19 14:22 /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20231008154809-if00 -> ../../ttyACM0
```

I can only get the USB device to work if I change the group ownership of `../../ttyACM0` to group `core`.
Now I would like to create an ignition file (or actually a butane file) how would I do that? 

I already tried adding user `core` to group `tty` but it appears the device is created with group ownership `dailout`, a group that does not exist on flatcar (yet is shown in ls -al):
```
$ getent group tty
tty:x:5:
 $ getent group dailout
 $ ls -al /dev/tty*
<SNIP>
crw--w----. 1 root tty       4, 60 Jan 19 14:22 /dev/tty60
crw--w----. 1 root tty       4, 61 Jan 19 14:22 /dev/tty61
crw--w----. 1 root tty       4, 62 Jan 19 14:22 /dev/tty62
crw--w----. 1 root tty       4, 63 Jan 19 14:22 /dev/tty63
crw--w----. 1 root tty       4,  7 Jan 19 14:22 /dev/tty7
crw--w----. 1 root tty       4,  8 Jan 19 14:22 /dev/tty8
crw--w----. 1 root tty       4,  9 Jan 19 14:22 /dev/tty9
crw-rw----. 1 root core    166,  0 Jan 19 14:22 /dev/ttyACM0
crw-------. 1 core tty       4, 64 Jan 19 14:22 /dev/ttyS0
crw-rw----. 1 root dialout   4, 65 Jan 19 14:22 /dev/ttyS1
crw-rw----. 1 root dialout   4, 66 Jan 19 14:22 /dev/ttyS2
crw-rw----. 1 root dialout   4, 67 Jan 19 14:22 /dev/ttyS3
crw-------. 1 root root      5,  3 Jan 19 14:22 /dev/ttyprintk

```
So how can I solve this using butane?

**Comment by tormath1** [comment, marked as answer]
Hello @ddt3,

Did you have a look to those examples: https://www.flatcar.org/docs/latest/setup/customization/adding-users/#add-users-via-butane-configs ? 

This configuration should add the `core` user to the `dialout` (use `tty` if you want `tty`) group:
```yaml
variant: flatcar
version: 1.1.0
storage:
  files:
    - path: /etc/userdb/core:dialout.membership
      contents:
        inline: " "
```

Please note the typo in your initial message too - `dialout` vs `dailout`:
```
$ getent group dialout
dialout:x:249:
```

**Reply by ddt3** [reply]
I think my typo is the root cause of everything! <sigh>
I actually created a butane with this information: 
```
variant: flatcar
version: 1.0.0
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - "ssh-rsa <snip>"
      groups:
        - tty 
        - daillout
        - docker
```
(with the same typo)
Maybe I should clean my glasses more often

I will change the above and instead create a  userdb file

Thanks @tormath1 ! Sorry for wasting your time...
