### DISCUSSION TITLE
containerd v2.0 support in Flatcar

### DISCUSSION THREAD

**Discussion by eshaanm25** [flatcar/Flatcar#1631] [Q&A] [answered]
Hey Team! I was wondering if upgrading to containerd v2.0 in Flatcar was being considered or in the works! containers v2.0 adds support for [User Namespaces](https://kubernetes.io/docs/concepts/workloads/pods/user-namespaces/) in K8s, and we'd love to start leveraging that feature in Kubernetes!

**Comment by tormath1** [comment, marked as answer]
Hello @eshaanm25,

Yes we are planning to do so, we're waiting for Docker to see when they will use Containerd 2.0. In the meantime, you can use sysext image to load containerd 2.0 on Flatcar. 

Here's a post I've made on Mastodon about it: https://fosstodon.org/@tormath1/113446694981085661

And the Butane configuration:
```yaml
variant: flatcar
version: 1.1.0
storage:
  links:
    - target: /opt/extensions/containerd/containerd-2.0.0-x86-64.raw
      path: /etc/extensions/containerd.raw
    - path: /etc/extensions/docker-flatcar.raw
      target: /dev/null
      overwrite: true
    - path: /etc/extensions/containerd-flatcar.raw
      target: /dev/null
      overwrite: true
  files:
    - path: /opt/extensions/containerd/containerd-2.0.0-x86-64.raw
      contents:
        source: https://github.com/flatcar/sysext-bakery/releases/download/latest/containerd-2.0.0-x86-64.raw
```

Let me know how it goes :)
