### ISSUE TITLE
NVIDIA GPUs: add documentation on how to use (for users), and pointers to ebuilds (for devs)

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#1034]

**Comment by pothos** [comment]
Sayan has a draft ready, will be filed as PR soon.

One possible improvement I noticed is that we could switch the `nvidia.service` unit to be `Type=oneshot` and `RemainAfterExit=true` and set `Before=containerd.service` to prevent race conditions with containers that want to use the GPU.

**Comment by sayanchowdhury** [comment]
PR  https://github.com/flatcar/flatcar-docs/pull/307

**Comment by shsamkit** [comment]
Is there any work going on related to chaning `nvidia.service` unit to `oneshot` type? It would really help with sequencing the service containers.
ATM `waitFor/required` doesn't really work with `nvidia.service` because it doesn't wait for the service to be actually completed.

**Comment by pothos** [comment]
I suggested it but didn't start the work, feel free to file a PR with the above suggestions.

**Comment by shsamkit** [comment]
@pothos Looks like there may not be a need for changing the service-type afterall. I was able to change the service-type using the [drop-in-units](https://www.flatcar.org/docs/latest/setup/customization/using-nvidia/)

If you want to try it out, this is the butane config I used 
```
---
variant: flatcar
version: 1.0.0
storage:
  files:
    - path: /etc/systemd/system/nvidia.service.d/service-type-simple.conf
      contents:
        inline: |
          [Service]
          Type=oneshot
```
