### ISSUE TITLE
CAPI images through systemd-sysext (system extensions) for easy CAPI updates

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#1061]
## Current situation

CAPI images are built through a combination of Packer+Ansible to set up the required state in the rootfs. The customizations done are a mix of new systemd services, binaries, and OS settings. The result is a custom cloud image.

## Impact

Updating to a newer version requires provisioning a new cloud instance, throwing the old away.

## Ideal future situation

Instead of using Packer+Ansible for image customization, all customization is contained in a systemd-sysext image (system extension image). This extension image can be swapped out easily to update the cloud instance to a new CAPI version.

The extension image can either be pulled at provisioning time (through Ignition) which has the benefit of being able to use vanilla marketplace images instead of requiring custom cloud images. Or the extension image can be placed on the OS image and the result is a custom cloud image as before to reduce the provisioning time. Updating is done out of band. In the future Flatcar could also offer CAPI sysext images as official extensions, then the update is done together with the OS update because the comination of OS version and CAPI version is tested and released together.

## Implementation options

The script to build the sysext image can be done from scratch or it could be done by parsing a part of the image-builder Ansible configuration to have a single place of truth for versions etc.
But anyway, we probably don't want containerd as part of this extension.

The first stage would be a limited MVP that demonstrates the benefit of in-place updates and shows the new architecture.

This should become part of the sysext-bakery and be an independent extension so that users can update on their own schedule. A systemd-sysupdate unit can be defined that creates the kured flagfile for issuing the reboot (kured so that Ubuntu is also supported).

Then we should decide if we want to support Kubernetes as official extension which has the benefit of not needing systemd-sysupdate and having to update mechanisms. We also have to decide what version to support and how we transition from one to the next (Either we only support one version and auto-update that like Docker, or we support multiple versions similar to how the LTS stream can point to the latest LTS or to the major version stream – opt-out of “latest” means that at some point instances don’t get K8s updates anymore and need to switch - This needs more logic in update-engine, a motd warning, and we would have to build base-OS independent sysext images, where it’s probably better to point people at the systemd-sysext bakery’s update repo if they want to stay on one version).

> → I think having both an official extension with a certain version supported and an independent extension makes sense.
> 
> Tasks for the official extension: Build Kubernetes binaries and add required configuration and package it as systemd-sysext image, publish as release artifact and as signed update payload

↑ Won't work because K8s major updates need manual actions.

**Comment by pothos** [comment]
Mathieu started the PoC work here: https://github.com/flatcar/sysext-bakery/pull/14

**Comment by tormath1** [comment]
FYI, the PoC has been merged and here's the Butane configuration to enable the update using `kured`:
```yaml
variant: flatcar
version: 1.0.0
systemd:
  units:
    - name: systemd-sysupdate.service
      enabled: true
storage:
  files:
    - path: /opt/extensions/kubernetes-1.26.6.raw
      mode: 0644
      contents:
        source: http://192.168.1.17:8000/kubernetes-1.26.6.raw
    - path: /etc/sysupdate.d/kubernetes.conf
      contents:
        inline: |
          [Transfer]
          Verify=false
          
          [Source]
          Type=url-file
          Path=http://192.168.1.17:8000/
          MatchPattern=kubernetes-@v.raw
          
          [Target]
          Type=regular-file
          Path=/opt/extensions/
          CurrentSymlink=/etc/extensions/kubernetes.raw
    - path: /etc/systemd/system/systemd-sysupdate.service.d/10-kubernetes.conf
      contents:
        inline: |
          [Service]
          ExecStartPost=/usr/bin/touch /run/reboot-required
  links:
    - path: /etc/extensions/kubernetes.raw
      hard: false
      target: /opt/extensions/kubernetes-1.26.6.raw
```

There is this Gist that runs a demo to update a single control-plane on QEMU: https://gist.github.com/tormath1/2e321943d91ecffd3a66786d8eeefa3c, I'll try to extend the PoC to CAPO later.

NOTE: :warning: Highly experimental
