### ISSUE TITLE
How to start Docker on boot should be documented

### ISSUE THREAD

**Issue by neilmayhew** [flatcar/Flatcar#134]
**Description**

By default in Flatcar, the docker service is socket-activated. It is possible to change this behaviour using an ignition config, but this isn't documented anywhere.

**Impact**

Any pre-existing containers that have the `restart` attribute set to `always` won't be started after a reboot until the docker socket is used (eg by `docker ps`).

It's not obvious how to change this.

**Environment and steps to reproduce**

1. **Set-up**: vanilla Flatcar with a default configuration
2. **Task**: Creating persistent containers that start on boot
3. **Action(s)**:
  a. Create a container with `restart` set to `always`
  b. Reboot
4. **Error**: Containers do not start until the docker socket is used (eg by `docker ps`).

**Expected behaviour**
Docker containers are up and running immediately after boot.

**Additional information**
Here's how it can be changed in `config.yaml`:

```yaml
systemd:
  units:
    # Ensure docker starts automatically instead of being socket-activated
    - name: docker.socket
      enabled: false
    - name: docker.service
      enabled: true
```

There should be a page documenting this and it should be linked from the FAQ.
