### ISSUE TITLE
Flat car systemd is crashing after OS update version from Flatcar-stable-3760.2.0-hvm

### ISSUE THREAD

**Issue by shankar-vng** [flatcar/Flatcar#1363]
## Description

Systemd along with all process targets seems to crash in AWS X86 flat car ami **Flatcar-stable-3815.2.0-hvm** until we force update back to **version 3760.2.0**

while looking at the [comments](https://github.com/flatcar/Flatcar/issues/1342#issuecomment-1946100302) on the issue, it seems the issue could be with the **bootstrap config** which i'm enclosing below

At this point, we are not sure whether the issue is originating from OS bootstrap config or from the ami itself

## Impact

None of the systemd targets (including Containderd & kubelet) are running which takes down all of K8s infrastructure on the node

## Environment and steps to reproduce

@t-lo I'm enclosing the boot Strap config which gets loaded as part of flat car OS bootstrapping which may be conflicting with flatcar OS ignition bootstrap process. Appreciate if you could point us to any conflicts that might be interfering with the systemd bootstrapping

[osp-flatcar.yml.zip](https://github.com/flatcar/Flatcar/files/14298792/osp-flatcar.yml.zip)

Including Journal logs

[Journal_log.zip](https://github.com/flatcar/Flatcar/files/14299373/Journal_log.zip)

## Expected behavior

Systemd units should get bootstrapped instead of crashing

**Comment by tormath1** [comment]
As mentioned on Matrix, it seems to be related to the line 681 of the provided bootstrap configuration:
```yaml
      - content:
          inline:
            data: |
              [Service]
              EnvironmentFile=/run/metadata/torcx
              Environment=CONTAINERD_CONFIG=/etc/containerd/config.toml
              ExecStart=
              ExecStart=/usr/bin/env PATH=${TORCX_BINDIR}:${PATH} ${TORCX_BINDIR}/containerd --config ${CONTAINERD_CONFIG}
        path: /etc/systemd/system/containerd.service.d/10-custom.conf
        permissions: 644
```

In the last Stable, Torcx has been removed in favor of systemd-sysext https://www.flatcar.org/releases#release-3815.2.0:
> torcx was replaced by systemd-sysext in the OS image

You might be interested to update your bootstrap config (i.e remove the `EnvironmentFile=/run/metadata/torcx`and drop the `ExecStart` overriding)

More on that here: https://www.flatcar.org/blog/2023/12/extending-flatcar-say-goodbye-to-torcx-and-hello-to-systemd-sysext/
