### ISSUE TITLE
Terraform: InvalidUserData.Malformed: User data is limited to 16384 bytes.

### ISSUE THREAD

**Issue by ethicalmohit** [flatcar/Flatcar#143]
**Description**

In cloud config in coreos. I used to mention encoding in terraform and also In YAML while passing file content. There was no issue with the same content to pass. But now If using container Linux config and converting it into ignition I am facing the below issue, Its exceeding in size. I am not able to find the related document on how to pass multiple files in container Linux with encoded string. 

```
InvalidUserData.Malformed: User data is limited to 16384 bytes.
	status code: 400, request id: f2f41409-d458-4c7a-9e58-9eac39547f20
```

Before:
```
write_files:
    -
        path: "/opt/bin/script"
        permissions: "0755"
        owner: "root"
        encoding: "base64"
        content: |
```

Now:
```
  files:  
    - filesystem: root
      path: "/opt/bin/script"
      mode: 0755
      contents: 
        inline: |
          ${script}
```

**Impact**

Unable to pass multiple files in user-data.

What is the correct way to pass it ?

**Comment by margamanterola** [comment]
Hi Mohit!

The error you're getting refers to the length of the generated userdata not to having several files.  I have working configs that store several files using the format you indicated and it works fine:

```
  files:
    - path: /etc/ssh/sshd_config
      filesystem: root
      mode: 0644
      contents:
        inline: |
          # Our sshd configuration.
          PasswordAuthentication no
          # etc etc
    - path: /etc/flatcar/update.conf
      filesystem: root
      mode: 0644
      contents:
        inline: |
          GROUP=stable
          REBOOT_STRATEGY=off
```

I suspect the problem you're facing is that your config has grown so large that it doesn't fit within the maximum limit anymore. You'll probably need to trim it to the essential parts to get the machine to boot and then handle the non-essential ones with another tool, like ansible, puppet, chef, etc. Or maybe you can check if you really need all that data?

**Comment by echomohit** [comment]
> Hi Mohit!
> 
> The error you're getting refers to the length of the generated userdata not to having several files. I have working configs that store several files using the format you indicated and it works fine:
> 
> ```
>   files:
>     - path: /etc/ssh/sshd_config
>       filesystem: root
>       mode: 0644
>       contents:
>         inline: |
>           # Our sshd configuration.
>           PasswordAuthentication no
>           # etc etc
>     - path: /etc/flatcar/update.conf
>       filesystem: root
>       mode: 0644
>       contents:
>         inline: |
>           GROUP=stable
>           REBOOT_STRATEGY=off
> ```
> 
> I suspect the problem you're facing is that your config has grown so large that it doesn't fit within the maximum limit anymore. You'll probably need to trim it to the essential parts to get the machine to boot and then handle the non-essential ones with another tool, like ansible, puppet, chef, etc. Or maybe you can check if you really need all that data?

This is true because now in the ignition there is no compression/encoding method type i can use to send the data to it. Is there any other way out ?

**Comment by margamanterola** [comment]
You can have ignition download the contents of the big files from a different source.  This is documented here: https://docs.flatcar-linux.org/container-linux-config-transpiler/doc/examples/#storage-and-files

```
storage:
  files:
    - path: /opt/file2
      filesystem: root
      contents:
        remote:
          url: http://example.com/file2
          compression: gzip
          verification:
            hash:
              function: sha512
              sum: 4ee6a9d20cc0e6c7ee187daffa6822bdef7f4cebe109eff44b235f97e45dc3d7a5bb932efc841192e46618f48a6f4f5bc0d15fd74b1038abf46bf4b4fd409f2e
      mode: 0644
```
