### ISSUE TITLE
No network at docker container level (whereas everything is OK inside flatcar server).

### ISSUE THREAD

**Issue by SR-G** [flatcar/Flatcar#1552]
## Description

I have a NUC running flatcar, installed one year ago and never rebooted. 
With only a docker installation inside it.
After today's reboot, i'm now with the latest FLATCAR images, but i can't access anymore the ports exposed out of my docker containers.

## Impact

Running docker containers are unusable.

## Environment and steps to reproduce

Not sure it will allow to "reproduce", but here are the symptoms.

FLATCAR : 
- running on a x86 NUC
- running with a USB key with ipxe.iso, reaching a "netbootd" server exposing the config, manifests, ... for the corresponding MAC management + the mirroring of the FLATCAR image
- FLATCAR customization is very light (NVME attached, SSH KEYS deployed ... that's all)
- current version is : `Linux FLATCAR-SERVER-1 6.6.48-flatcar #1 SMP PREEMPT_DYNAMIC Wed Sep  4 15:49:08 -00 2024 x86_64 AMD Ryzen 5 3450U with Radeon Vega Mobile Gfx AuthenticAMD GNU/Linux` 

CONTEXT : 
- Last reboot was one year ago !
- I rebooted today, now have a newer FLATCAR version - everything has restarted fine after reboot, including the containers

SYMPTOMS : 
- containers are running - example : `3887f9e5c368   victoriametrics/victoria-metrics   "/victoria-metrics-p…"   37 minutes ago   Up 20 minutes   0.0.0.0:8428->8428/tcp   victoria-metrics` (note that the "8428" port is exposed and should be accessible from the outside of the container)
- if i "curl" the exposed port from FLATCAR, it does not work ! : `# curl 127.0.0.1:8428
curl: (56) Recv failure: Connection reset by peer`
- of course same if i try from another server on the same network at home
- same with `localhost:8428`
- if i enter into the container `docker exec -it victoria-metrics /bin/ash`, then i also have NO network there : 
```
/ # ping 1.1.1.1 # <---------- this should have worked ! (it's working from the host = from flatcar)
PING 1.1.1.1 (1.1.1.1): 56 data bytes
^C
--- 1.1.1.1 ping statistics ---
20 packets transmitted, 0 packets received, 100% packet loss
/ # ping 192.168.8.190 # <---------- this is the IP of the host
PING 192.168.8.190 (192.168.8.190): 56 data bytes
^C
--- 192.168.8.190 ping statistics ---
6 packets transmitted, 0 packets received, 100% packet loss
/ # ping 192.168.8.1  # <---------- this is the router
PING 192.168.8.1 (192.168.8.1): 56 data bytes
^C
--- 192.168.8.1 ping statistics ---
3 packets transmitted, 0 packets received, 100% packet loss
```

(every ping is stuck for a while so i CTRL-C)

What i tryed (without luck) : 
- Reboot FLATCAR (does not help)
- Export all containers, stop docker, delete the /var/lib/docker content, to re-start docker side from scratch : after reboot, docker recreates everything (including network) but still no luck !
- Analyze the `docker inspect`, especially the network part : nothing wrong !
- Disable (per FLATCAR configuration) IPV6 (just in case), with extra parameter in the list of kernel parameters at boot : IPv6 is correctly disabled, but still no luck 
- Of course i tried with other containers (NGINX, NETDATA, ...) : exact same problem
- Start the container with `--net=host` (so no ports exposed) : here of course, everything works (the port is accessible from the host / from other servers + from the inside of the container, i can reach any IP outside it) - but of course, this is not the proper / possible solution

As far as i can tell, i would really say it's somehow FLATCAR related and not DOCKER related ... but i'm really stuck / i can't find any idea of what may be wrong.

## Expected behavior

Network to be working

## Additional information

IFCONFIG (there is 2 RJ45 port, only one is plugged at this time) : 
``` 
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:80:98:0d:80  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1  bytes 333 (333.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

enp3s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.8.190  netmask 255.255.255.0  broadcast 192.168.8.255
        ether 1c:83:41:29:50:a5  txqueuelen 1000  (Ethernet)
        RX packets 14509  bytes 1357301 (1.2 MiB)
        RX errors 0  dropped 310  overruns 0  frame 0
        TX packets 7739  bytes 927912 (906.1 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

enp4s0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 1c:83:41:29:50:a6  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 28  bytes 2239 (2.1 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 28  bytes 2239 (2.1 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth2c0e65d: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        ether 96:f6:07:07:c9:8f  txqueuelen 0  (Ethernet)
        RX packets 32  bytes 3259 (3.1 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 32  bytes 10074 (9.8 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

```

DOCKER INSPECT : 
```
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "b8a190a887024e9556004186b7b4fc72864ebc296f092c02096764d86cf28640",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "8428/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8428"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/b8a190a88702",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "a4193978e3cf39f76460767a89325ae9de24265d57e5de0da2eacb21cc394a26",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "7920200b13641722ddfefba9257ad61f0eb1f87da2daa7d13dd2ed718773d722",
                    "EndpointID": "a4193978e3cf39f76460767a89325ae9de24265d57e5de0da2eacb21cc394a26",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02",
                    "DriverOpts": null
                }
            }
        }
```
(i compared everything from that JSON with another containers in a non-flatcar environment, and no special/structural differences)

ETC/HOSTS (nothing special)

```
# /etc/hosts: Local Host Database
#
# This file describes a number of aliases-to-address mappings for the for 
# local hosts that share this file.
#
# The format of lines in this file is:
#
# IP_ADDRESS	canonical_hostname	[aliases...]
#
#The fields can be separated by any number of spaces or tabs.
#
# In the presence of the domain name service or NIS, this file may not be 
# consulted at all; see /etc/host.conf for the resolution order.
#

# IPv4 and IPv6 localhost aliases
127.0.0.1	localhost
::1		localhost

#
# Imaginary network.
#10.0.0.2               myname
#10.0.0.3               myfriend
#
# According to RFC 1918, you can use the following IP networks for private 
# nets which will never be connected to the Internet:
#
#       10.0.0.0        -   10.255.255.255
#       172.16.0.0      -   172.31.255.255
#       192.168.0.0     -   192.168.255.255
#
# In case you want to be able to connect directly to the Internet (i.e. not 
# behind a NAT, ADSL router, etc...), you need real official assigned 
# numbers.  Do not try to invent your own network numbers but instead get one 
# from your network provider (if any) or from your regional registry (ARIN, 
# APNIC, LACNIC, RIPE NCC, or AfriNIC.)
#
```
NETSTAT seems fine ... : 

```
netstat -a -n -p |grep 8428
tcp        0      0 0.0.0.0:8428            0.0.0.0:*               LISTEN      2179/docker-proxy   
```

and

```
 ps -ef|grep docker-proxy
root        2179    1391  0 22:34 ?        00:00:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 8428 -container-ip 172.17.0.2 -container-port 8428
```

**Comment by jepio** [comment]
Check the output of these on host:
```
sudo iptables -vnL
sysctl net.ipv4.ip_forward
```

**Comment by SR-G** [comment]
Yeah i found some info related to "ip_forward" yesterday and also checked it at that time : it seems OK for "ip_forward" (= 1). 

I'm not able to interpret the firewall rules ... (but how could them be wrong, as they've not been altered in any way = i've not configured anything or tried anything about this).

Here are the results : 

```
FLATCAR-SERVER-1 ~ # iptables -vnL
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
   46  3864 DOCKER-USER  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
   46  3864 DOCKER-ISOLATION-STAGE-1  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
   23  1932 ACCEPT     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 DOCKER     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  docker0 docker0  0.0.0.0/0            0.0.0.0/0           

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain DOCKER (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     tcp  --  !docker0 docker0  0.0.0.0/0            172.17.0.2           tcp dpt:8428

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DOCKER-ISOLATION-STAGE-2  all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0           
   46  3864 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain DOCKER-ISOLATION-STAGE-2 (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DROP       all  --  *      docker0  0.0.0.0/0            0.0.0.0/0           
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain DOCKER-USER (1 references)
 pkts bytes target     prot opt in     out     source               destination         
   46  3864 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0           


FLATCAR-SERVER-1 ~ # sysctl net.ipv4.ip_forward
net.ipv4.ip_forward = 1
```

**Comment by ader1990** [comment]
Hello,

I would suggest to test a minimal scenario and see if it works with the new Flatcar image you have.
Maybe there is an issue in some other place, which is not clearly visible.

Can you try to start a new nginx container with an exposed port (12301 - I chose it randomly), and then try to curl it:

```
docker run -d -p 12301:80 --name test-exposed-ports nginx:latest
sleep 10
curl http://localhost:12301
```

`These steps worked on my clean Flatcar env`. If it does not work on yours, we can compare the network details.

Thanks.

**Comment by SR-G** [comment]
Have just tried, and still same behavior : 

``` 
FLATCAR-SERVER-1 ~ # docker run -d -p 12301:80 --name test-exposed-ports nginx:latest
Unable to find image 'nginx:latest' locally
latest: Pulling from library/nginx
Digest: sha256:b5d3f3e104699f0768e5ca8626914c16e52647943c65274d8a9e63072bd015bb
Status: Downloaded newer image for nginx:latest
75a7fe4439dac8085de6b8d0ca4ff8263d264003699dd0c27ce91b80ade83dcd


FLATCAR-SERVER-1 ~ # sleep 10


FLATCAR-SERVER-1 ~ # curl http://localhost:12301
curl: (56) Recv failure: Connection reset by peer
```

**Comment by ader1990** [comment]
Do you happen to know from which Flatcar version did you upgrade, to help reproduce the issue?

**Comment by SR-G** [comment]
I can post my IGNITION details, but i don't think it's really related (however ... maybe it was OK with that old revision and not anymore with the new versions ? For example : i'm exposing (as it's local network / homelab usage) the 2375 docker port outside of the host) : 

Ignition (a bit simplified here about non-related topics like SSH keys) : 

```json
passwd:
  users:
    - name: root
      password_hash: "REMOVED"
      ssh_authorized_keys: "REMOVED"

storage:
  links:
    # Set proper timezone
    - path: /etc/localtime
      filesystem: root
      overwrite: true
      target: /usr/share/zoneinfo/Europe/Paris

  files:
    # we force same SSH config all the time
    - path: /etc/hostname
      filesystem: root
      mode: 0644      
      contents:
        inline: FLATCAR-SERVER-1
    - path: /etc/ssh/ssh_host_dsa_key(extra_sections_REMOVED)

systemd:
  units:

    # Mount NVME to /var/lib/docker
    # Has to be partitioned & formatted manually before !
    - name: var-lib-docker.mount
      enabled: true
      contents: |
        [Unit]
        Description=Mount NVME to /var/lib/docker
        Before=local-fs.target
        [Mount]
        What=/dev/nvme0n1p1
        Where=/var/lib/docker
        Type=ext4
        [Install]
        WantedBy=local-fs.target

    # We want docker (service) to be automatically started instead of starting docker
    # when needed through its socket
    # - name: docker.socket
    #   enabled: false

    - name: docker.service
      enabled: true
      dropins:
        - name: 10-wait-docker.conf
          contents: |
            [Unit]
            After=var-lib-docker.mount
            Requires=var-lib-docker.mount            

    - name : containerd.service
      enabled: true

    # Expose docker socket over tcp = over the network
    - name: docker-tcp.socket
      enabled: true
      contents: |
        [Unit]
        Description=Docker Socket for the API

        [Socket]
        ListenStream=2375
        BindIPv6Only=both
        Service=docker.service

        [Install]
        WantedBy=sockets.target
```

The "manifest" exposing the image (i just added here at the end the disabling of IPv6) : 

```
---
# This example manifest boots Ubuntu 20.04 into ram using tmpfs-mounted root filesystem downloaded over HTTP
id: flatcar-server-1
# ipv4: 192.168.17.103/24
ipv4: 192.168.8.190/24
hostname: flatcar-server-1
domain: test.local
leaseDuration: 1h

# many values are possible because a single machine may have multiple interfaces
# and it may not be known which one boots first
mac:
  - 1c:83:41:29:50:a5
  - 1c:83:41:29:50:a6

# in the "order of preference"
dns:
  - 8.8.8.8
  - 8.8.4.4

# in the "order of preference"
router:
  - 192.168.8.1

# in the "order of preference"
ntp:
  - 192.168.8.1

ipxe: true
bootFilename: install.ipxe

mounts:
  - path: /images
    pathIsPrefix: true
    proxy: http://stable.release.flatcar-linux.net/amd64-usr/current
    appendSuffix: true
    # localDir: /opt/netbootd/images/

  - path: /common
    pathIsPrefix: true
    localDir: /opt/netbootd/configs/common
    appendSuffix: true

  - path: /configs
    # When true, all paths starting with this prefix use this mount.
    pathIsPrefix: true
    # Provides a path on the host to find the files.
    # So that localDir: /tftpboot path: /subdir and client request: /subdir/file.x so that the host
    # path becomes /tfptboot/file.x
    localDir: /opt/netbootd/configs/flatcar-server-1
    # When true, the localDir path defined above gets a suffix to the Path prefix appended to it.
    appendSuffix: true

  - path: /install.ipxe
    content: |
      #!ipxe
      # set base-url http://stable.release.flatcar-linux.net/amd64-usr/current
      set base-url {{ .HttpBaseUrl }}/images
      kernel ${base-url}/flatcar_production_pxe.vmlinuz initrd=flatcar_production_pxe_image.cpio.gz flatcar.first_boot=1 ignition.config.url={{ .HttpBaseUrl.String }}/configs/flatcar.ign ipv6.disable=1
      initrd ${base-url}/flatcar_production_pxe_image.cpio.gz
      boot     
```
