### ISSUE TITLE
nfs mount problems because of start-statd and PATH

### ISSUE THREAD

**Issue by xeor** [flatcar/Flatcar#161]
**Description**

Kubernetes not able to run /usr/sbin/start-statd on nfs mounts, because of PATH?

**Impact**

Unable to use simple nfs mounts inside containers without using `-o nolock`

**Environment and steps to reproduce**

1. **Set-up**: Setup a normal k8s cluster, no special requirements. You also need an nfs share.
2. **Action**: Try creating a pod, like this:

```
kind: Pod
apiVersion: v1
metadata:
  name: nfs-test-pod
spec:
  containers:
    - name: pod
      image: alpine
      command: ["sleep", "9999999"]
      volumeMounts:
      - mountPath: "/data"
        name: data
  volumes:
    - name: data
      nfs:
        path: /data
        server: 10.1.2.3
```

3. **Error**: Dedscribe the pod, and see an error like:

```
Mounting command: mount
Mounting arguments: -t nfs 10.1.2.3:/data /var/lib/kubelet/pods/2a8a9a3e-e4fd-47b3-9b22-595f94b9babe/volumes/kubernetes.io~nfs/data
Output: /usr/sbin/start-statd: line 23: systemctl: command not found
mount.nfs: rpc.statd is not running but is required for remote locking.
mount.nfs: Either use '-o nolock' to keep locks local, or start statd.
  Warning  FailedMount  13s (x14 over 34m)  kubelet, d1.lan  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[data default-token-t28c7]: timed out waiting for the condition
```

**Expected behavior**
/usr/sbin/start-statd on the node is run as it should, starting statd.

**Additional information**

To temporary fix the problem, `ssh admin@d1.lan sudo /usr/sbin/start-statd` works.

The fix might be to change `systemctl` to `/usr/bin/systemctl` in the `/usr/sbin/start-statd` script, or fix the PATH for whoever is calling this script.

**Comment by xeor** [comment]
The `start-statd` is an upstream script, so I guess the better approach to fix this would be to
* make a symlink to it from another /bin (that is in the PATH)
* correct the PATH for whoever calls it. Anyone with an idea of whom?

**Comment by margamanterola** [comment]
I've checked the contents of `/usr/sbin/start-statd` in both the stable and alpha channels of Flatcar and they both have this line as the first uncommented line:

```
PATH="/sbin:/usr/sbin:/bin:/usr/bin"
```

Which version of Flatcar are you running? Can you show the full contents of `/usr/sbin/start-statd`?

**Comment by xeor** [comment]
I tried this just now using `2512.4.0`, and the problem is still there. There `PATH` variable is, as you say set. I can see that in mine as well, however, the error is still `/usr/sbin/start-statd: line 23: systemctl: command not found`.
systemctl is in both under `/bin/systemctl` and `/usr/bin/systemctl`

I'm not sure how to debug this since start-statd is from the nfs-utils package and /usr/ is read-only..

**Comment by xeor** [comment]
Mounting manually like `/sbin/mount.nfs 10.1.2.3:/data tmpmount` works.

I tried doing a bind-mount to overwrite whats under /usr/sbin on the os so I could change the start-statd script. My changes didnt have any effect, so maybe this is run inside a container (which doesnt get affected by bind-mounts).

Maybe this is happening inside the `kubelet` container? systemctl inside there is under /host/usr/bin/systemctl, and running it still gives an error `/host/usr/bin/systemctl: error while loading shared libraries: libsystemd-shared-241.so: cannot open shared object file: No such file or directory`.

**Comment by margamanterola** [comment]
So, how are you running the kubelet?

**Comment by xeor** [comment]
Thats a good question... I'm using rancher and `rke`. Problem might not be that easy to fix then..

The best soluition might be just putting something like this in the flatcar install-yaml if you know you are going to mount nfs shares, but are running the kubelet inside a container. I've didnt test this during the install..

```
systemd:
  units:
    - name: rpc-statd.service
      enabled: true
      dropins:
        - name: 10-install.conf
          contents: |
            [Install]
            WantedBy=multi-user.target
```

To enable withouit reinstall

```
mkdir /etc/systemd/system/rpc-statd.service.d/
echo -e "[Install]\nWantedBy=multi-user.target" > /etc/systemd/system/rpc-statd.service.d/10-install.conf
systemctl daemon-reload
systemctl enable rpc-statd
systemctl start rpc-statd
```
