### ISSUE TITLE
Cannot start custom image toolbox after using flatcar-reset

### ISSUE THREAD

**Issue by ryester19** [flatcar/Flatcar#1690]
I have the following contents present in my Butane/Ignition config:
```
storage:
  files:
    - path: /home/core/.toolboxrc
      mode: 0644
      contents:
        inline: |
          TOOLBOX_DOCKER_IMAGE=docker.io/library/alpine
          TOOLBOX_USER=root
```
I have no issues launching the toolbox right after booting Flatcar for the first time on a new installation.

When I use `flatcar-reset` (without arguments), and then try to launch the toolbox after reboot, I'm met with this error:
```
unpacking linux/amd64 sha256:a8560b36e8b8210634f77d9f7f9efd7ffa463e380b75e2e74aff4511df3ef88c...
ctr: failed to prepare extraction snapshot "extract-303398294-eHgJ sha256:08000c18d16dadf9553d747a58cf44023423a9ab010aab96cf263d2216b8b350": failed to rename: rename /var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/new-4126173960 /var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/1: file exists: unknown
```
Removing the contents of `/var/lib/containerd` manually does allow me to start the Alpine toolbox again

**Comment by tormath1** [comment]
Hi @ryester19 and thanks for the report,

When you restart after a `flatcar-reset` it's similar to reboot from a fresh install so your custom configuration is wiped out.
```
storage:
  files:
    - path: /home/core/.toolboxrc
      mode: 0644
      contents:
        inline: |
          TOOLBOX_DOCKER_IMAGE=docker.io/library/alpine
          TOOLBOX_USER=root
```

I think before the error message:
```
ctr: failed to prepare extraction snapshot "extract-303398294-eHgJ sha256:08000c18d16dadf9553d747a58cf44023423a9ab010aab96cf263d2216b8b350": failed to rename: rename /var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/new-4126173960 /var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/1: file exists: unknown
```

You might even see that it does not use the `alpine` image but the default `fedora` one.

If you want to `flatcar-reset` without running Ignition again, you can try to create your configuration here: `/etc/default/toolbox` then run `flatcar-reset -K /etc/default/toolbox`. 

Let us know how things are working.
