### ISSUE TITLE
vlan kernel arg fails to set VLAN ID

### ISSUE THREAD

**Issue by tcldr** [flatcar/Flatcar#1706]
## Description

When supplying kernel arguments via the ignition `kernel_arguments` clause, the specified VLAN ID is ignored.

## Impact

Unable to bootstrap Flatcar instance in environments that require networking through a VLAN.

## Environment and steps to reproduce

1. **Set-up**:
  - Create a config with the following spec:
  ```
  variant: flatcar
  version: 1.1.0

  kernel_arguments:
  should_exist:
    - ip=10.0.2.101::10.0.2.1:255.255.255.0:worker-1:eth0.4000:off:1400
    - nameserver=185.12.64.1
    - nameserver=185.12.64.2
    - vlan=eth0.4000:eth0
  ```
  - Launch in QEMU with a fresh image
3. **Task**:
  - Initial boot
5. **Action(s)**:
  - n/a
4. **Error**:
  - `eth0.4000: VLAN without valid Id (65535) configured in /run/systemd/network/70-eth0.4000.netdev` (journalctl)

## Expected behavior

Network created with the specified VLAN ID of 4000.

## Additional information

It appears the configuration created by systemd-network-generator is missing the VLAN section with the VLAN ID in the `.netdev` file. This generates the "VLAN without valid Id (65535)" max int error.

```
core@localhost ~ $ cat /run/systemd/network/70-eth0.4000.netdev 
# Automatically generated by systemd-network-generator

[NetDev]
Kind=vlan
Name=eth0.4000
```

```
core@localhost ~ $ cat /run/systemd/network/70-eth0.4000.network 
# Automatically generated by systemd-network-generator

[Match]
Name=eth0.4000

[Link]
MTUBytes=1400

[Network]
DHCP=no
LinkLocalAddressing=no
IPv6AcceptRA=no
DNS=185.12.64.1
DNS=185.12.64.2

[DHCP]
Hostname=worker-1

[Address]
Address=10.0.2.101/24

[Route]
Gateway=10.0.2.1
```

I've tried every variation of kernel vlan naming specified in the dracut docs – VLAN_PLUS_VID (vlan0005), VLAN_PLUS_VID_NO_PAD (vlan5), DEV_PLUS_VID (eth0.0005), DEV_PLUS_VID_NO_PAD (eth0.5) – but none of them generate a VLAN ID. I also tried with lower VLAN IDs  in case there's an unknown threshold – no luck there either.

A working .netdev file should look something like:
```
[NetDev]
Name=eth0.4000
Kind=vlan
MTUBytes=1400 # I assume this is OK in the .network file instead, but usually I'd place here.

[VLAN]
Id=4000
```
