### ISSUE TITLE
Login via SSH fails after rebooting from a power outage.

### ISSUE THREAD

**Issue by reaper8055** [flatcar/Flatcar#1757]
## Description

SSH authorized_keys files are corrupted or lost during power outages, resulting in complete system lockout when no password authentication is configured. The root cause appears to be that Ignition provisions SSH keys only during first boot with no automatic recovery mechanism for filesystem corruption caused by unexpected power loss.

![Image](https://github.com/user-attachments/assets/fb23edb0-540e-4b73-8764-658381d69cff)

## Impact

Power outages result in complete system lockout, requiring full system reinstallation to regain access.

## Environment and steps to reproduce

1. **Set-up**: Flatcar Linux installed on bare metal hardware using ISO installation method with Ignition configuration containing SSH authorized_keys for the core user, no password authentication configured
2. **Task**: Normal system operation after successful initial provisioning via Ignition
3. **Action(s)**: 
  a. System successfully provisioned with SSH keys working normally
  b. Power outage occurs (or simulated via hard power off)
  c. System rebooted after power restoration
  d. SSH connection attempted using previously working key
4. **Error**: SSH authentication fails with "Permission denied (publickey,keyboard-interactive)" despite using correct private key, system prompts for password which was never configured

## Expected behavior

SSH key authentication should continue working after power outages. The system should either maintain key integrity through robust filesystem handling or provide automatic recovery mechanisms to restore SSH access.

## Additional information

1. **Reproduction confirmed:** This issue is consistently reproducible by simulating power failures on freshly installed Flatcar systems.

2. **Installation method:** Bare metal installation using Flatcar ISO with command: `sudo flatcar-install -d /dev/sda -i flatcar.json`. Used this cmd to get the `flatcar.json`:  `docker run --rm -i quay.io/coreos/butane:release --pretty --strict < flatcar.yml > flatcar.json` 

3. **Technical analysis:** Ignition provisions SSH keys during first boot but provides no recovery mechanism when `/home/core/.ssh/authorized_keys` becomes corrupted or lost due to filesystem inconsistency from power outages.

4. **Diagnostic evidence:** After power outage, `/home/core/.ssh/authorized_keys` is either missing, empty, or has corrupted permissions, preventing SSH daemon from reading the keys.

5. **Suggested solution:** Flatcar should include automatic SSH key recovery mechanisms to restore authorized_keys from the original Ignition configuration when missing or corrupted.

Complete Ignition configuration used:

```yaml
variant: flatcar
version: 1.0.0

passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBci1xz1g+pS9xs+KA6ymADE4w5rlrf+AXiQSP/mE/uH flatcar-spacectl'
      groups: [ sudo, docker ]

storage:
  files:
    - path: /etc/flatcar/update.conf
      overwrite: true
      mode: 0644
      contents:
        inline: |
          REBOOT_STRATEGY=best-effort

    - path: /etc/hostname
      mode: 0644
      contents:
        inline: athena.spacectl.arpa

    - path: /etc/sudoers.d/core
      mode: 0440
      contents:
        inline: |
          core ALL=(ALL) NOPASSWD: ALL

    - path: /etc/systemd/network/10-enp2s0.network
      mode: 0644
      contents:
        inline: |
          [Match]
          Name=enp2s0

          [Network]
          DHCP=yes
    - path: /etc/systemd/network/10-enp3s0.network
      mode: 0644
      contents:
        inline: |
          [Match]
          Name=enp3s0

          [Network]
          DHCP=yes
    - path: /etc/systemd/network/10-enp4s0.network
      mode: 0644
      contents:
        inline: |
          [Match]
          Name=enp4s0

          [Network]
          DHCP=yes
    - path: /etc/systemd/network/10-enp5s0.network
      mode: 0644
      contents:
        inline: |
          [Match]
          Name=enp5s0

          [Network]
          DHCP=yes
    - path: /etc/systemd/network/10-enp6s0.network
      mode: 0644
      contents:
        inline: |
          [Match]
          Name=enp6s0

          [Network]
          DHCP=yes

systemd:
  units:
    - name: sshd.service
      enabled: true

    - name: systemd-networkd.service
      enabled: true

    - name: update-engine.service
      enabled: true

    - name: locksmithd.service
      enabled: true
      mask: false
```

I also tried this version of yaml, but it didn't work either. 
```yaml
variant: flatcar
version: 1.0.0

passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBci1xz1g+pS9xs+KA6ymADE4w5rlrf+AXiQSP/mE/uH flatcar-spacectl'
      groups: [ sudo, docker ]

storage:
  files:
    - path: /etc/ssh/sshd_config.d/10-hardening.conf
      mode: 0644
      contents:
        inline: |
          PasswordAuthentication no
          PubkeyAuthentication yes
          PermitRootLogin no
          AuthorizedKeysFile .ssh/authorized_keys

    - path: /etc/flatcar/update.conf
      overwrite: true
      mode: 0644
      contents:
        inline: |
          REBOOT_STRATEGY=best-effort

    - path: /etc/hostname
      mode: 0644
      contents:
        inline: athena.spacectl.arpa

    - path: /etc/sudoers.d/core
      mode: 0440
      contents:
        inline: |
          core ALL=(ALL) NOPASSWD: ALL

    - path: /etc/systemd/network/10-enp2s0.network
      mode: 0644
      contents:
        inline: |
          [Match]
          Name=enp2s0

          [Network]
          DHCP=yes
    - path: /etc/systemd/network/10-enp3s0.network
      mode: 0644
      contents:
        inline: |
          [Match]
          Name=enp3s0

          [Network]
          DHCP=yes
    - path: /etc/systemd/network/10-enp4s0.network
      mode: 0644
      contents:
        inline: |
          [Match]
          Name=enp4s0

          [Network]
          DHCP=yes
    - path: /etc/systemd/network/10-enp5s0.network
      mode: 0644
      contents:
        inline: |
          [Match]
          Name=enp5s0

          [Network]
          DHCP=yes
    - path: /etc/systemd/network/10-enp6s0.network
      mode: 0644
      contents:
        inline: |
          [Match]
          Name=enp6s0

          [Network]
          DHCP=yes

systemd:
  units:
    - name: sshd.service
      enabled: true

    - name: systemd-networkd.service
      enabled: true

    - name: update-engine.service
      enabled: true

    - name: locksmithd.service
      enabled: true
      mask: false

    - name: ssh-key-recovery.service
      enabled: true
      contents: |
        [Unit]
        Description=Recover SSH keys if corrupted by power failure
        After=multi-user.target
        Before=sshd.service

        [Service]
        Type=oneshot
        ExecStart=/bin/bash -c 'if [[ ! -s /home/core/.ssh/authorized_keys ]]; then mkdir -p /home/core/.ssh && echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBci1xz1g+pS9xs+KA6ymADE4w5rlrf+AXiQSP/mE/uH flatcar-spacectl" > /home/core/.ssh/authorized_keys && chmod 700 /home/core/.ssh && chmod 600 /home/core/.ssh/authorized_keys && chown -R core:core /home/core/.ssh; fi'

        [Install]
        WantedBy=multi-user.target
```

**Comment by jepio** [comment]
This is weird - the `authorized_keys` file is generated and properly synced+renamed+synced for durability. https://github.com/flatcar/update-ssh-keys/blob/main/src/lib.rs#L348-L375

Can you show some examples of the way the file is corrupted? And can you say if the files under `.ssh/authorized_keys.d/` are in-tact? And how long after boot does the power outage have to be to cause issues.

As for recovery handling: by design ignition runs on the first boot only, and things are expected to be durable after that. For some reason this doesn't hold on your system. You can work around this by making sure ignition runs on every boot and recreates your configuration: see yaml below (added kernel_arguments and overwrite to all the entries). You may try this, but if your system is not ensuring filesystem durability you will run into other problems.

```yaml
variant: flatcar
version: 1.0.0
kernel_arguments:
  should_exist:
  - flatcar.first_boot=1

passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBci1xz1g+pS9xs+KA6ymADE4w5rlrf+AXiQSP/mE/uH flatcar-spacectl'
      groups: [ sudo, docker ]

storage:
  files:
    - path: /etc/flatcar/update.conf
      overwrite: true
      mode: 0644
      contents:
        inline: |
          REBOOT_STRATEGY=best-effort

    - path: /etc/hostname
      overwrite: true
      mode: 0644
      contents:
        inline: athena.spacectl.arpa

    - path: /etc/sudoers.d/core
      overwrite: true
      mode: 0440
      contents:
        inline: |
          core ALL=(ALL) NOPASSWD: ALL

    - path: /etc/systemd/network/10-enp2s0.network
      overwrite: true
      mode: 0644
      contents:
        inline: |
          [Match]
          Name=enp2s0

          [Network]
          DHCP=yes
    - path: /etc/systemd/network/10-enp3s0.network
      overwrite: true
      mode: 0644
      contents:
        inline: |
          [Match]
          Name=enp3s0

          [Network]
          DHCP=yes
    - path: /etc/systemd/network/10-enp4s0.network
      overwrite: true
      mode: 0644
      contents:
        inline: |
          [Match]
          Name=enp4s0

          [Network]
          DHCP=yes
    - path: /etc/systemd/network/10-enp5s0.network
      overwrite: true
      mode: 0644
      contents:
        inline: |
          [Match]
          Name=enp5s0

          [Network]
          DHCP=yes
    - path: /etc/systemd/network/10-enp6s0.network
      overwrite: true
      mode: 0644
      contents:
        inline: |
          [Match]
          Name=enp6s0

          [Network]
          DHCP=yes

systemd:
  units:
    - name: sshd.service
      enabled: true

    - name: systemd-networkd.service
      enabled: true

    - name: update-engine.service
      enabled: true

    - name: locksmithd.service
      enabled: true
      mask: false
```

**Comment by reaper8055** [comment]
> This is weird - the authorized_keys file is generated and properly synced+renamed+synced for durability. https://github.com/flatcar/update-ssh-keys/blob/main/src/lib.rs#L348-L375

Thanks for sharing this. I will have to take a look at the code.

> Can you show some examples of the way the file is corrupted? And can you say if the files under .ssh/authorized_keys.d/ are in-tact?

I am just speculating that the file is corrupted (sorry I did not make it clear in my issue description). I still have the machine and the instance running, I can probably live boot into a linux env and mount the partitions and check if the files are intact.

Output of `lsblk -f`:

```bash
NAME   FSTYPE   FSVER            LABEL      UUID                                 FSAVAIL FSUSE% MOUNTPOINTS
loop0  squashfs 4.0                                                                31.3G     0% /usr
loop3  squashfs 4.0
loop4  squashfs 4.0
sda
|-sda1 vfat     FAT32            EFI-SYSTEM B0A1-4901
|-sda2
|-sda3 btrfs                                4a916ed5-00fd-4e52-b8e2-9fed6d007e9f
|-sda4
|-sda6 btrfs                     OEM        e6cdb381-7cd1-4e2a-87c4-f7bcb12f058c
|-sda7
`-sda9 ext4     1.0              ROOT       21480c83-ef05-4682-ad3b-f751980943a0
sdb
|-sdb1 vfat     FAT32            EFI-SYSTEM B0A1-4901
|-sdb2
|-sdb3 btrfs                                4a916ed5-00fd-4e52-b8e2-9fed6d007e9f
|-sdb4
|-sdb6 btrfs                     OEM        94fdd1a6-0706-41e6-a3fb-a1983ef9d667
|-sdb7
`-sdb9 ext4     1.0              ROOT       21480c83-ef05-4682-ad3b-f751980943a0
sdc    iso9660  Joliet Extension CDROM      2025-04-29-23-40-24-37
`-sdc1 iso9660  Joliet Extension CDROM      2025-04-29-23-40-24-37
```

Output of `sudo fdisk -l /dev/sda`:

```bash
Disk /dev/sda: 111.79 GiB, 120034123776 bytes, 234441648 sectors
Disk model: Protectli 120GB
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 643CD9D2-1A3B-4FC7-95E3-10F559D25CAB

Device       Start       End   Sectors   Size Type
/dev/sda1     4096    266239    262144   128M EFI System
/dev/sda2   266240    270335      4096     2M BIOS boot
/dev/sda3   270336   2367487   2097152     1G unknown
/dev/sda4  2367488   4464639   2097152     1G unknown
/dev/sda6  4464640   4726783    262144   128M Linux filesystem
/dev/sda7  4726784   4857855    131072    64M unknown
/dev/sda9  4857856 234441614 229583759 109.5G unknown
```

Here's the partitions I mounted:

```bash
sudo mkdir -p /mnt/flatcar-data
sudo mount /dev/sda9 /mnt/flatcar-data

sudo mkdir -p /mnt/flatcar-root
sudo mount /dev/sda3 /mnt/flatcar-root

sudo mkdir -p /mnt/flatcar-system
sudo mount /dev/sda3 /mnt/flatcar-system
```

Output of `ls -la /mnt/flatcar-home/`:
(the symlinks were glowing red (possibly borken?) 

![Image](https://github.com/user-attachments/assets/9745732b-d97c-4031-be10-69692721617c)

```bash
total 92
drwxr-xr-x. 20 root root  4096 Jun  1 16:14 .
drwxr-xr-x.  5 root root   100 Jun  6 09:45 ..
drwxr-xr-x.  3 root root  4096 Jun  1 16:14 .etc-work
lrwxrwxrwx.  1 root root     7 Jun  1 16:14 bin -> usr/bin
drwxr-xr-x.  2 root root  4096 Apr 29 23:04 boot
drwxr-xr-x.  2 root root  4096 Jun  1 16:14 dev
drwxr-xr-x. 10 root root  4096 Jun  1 16:14 etc
drwxr-xr-x.  3 root root  4096 Jun  1 16:14 home
lrwxrwxrwx.  1 root root     7 Jun  1 16:14 lib -> usr/lib
lrwxrwxrwx.  1 root root     9 Jun  1 16:14 lib64 -> usr/lib64
drwx------.  2 root root 16384 Apr 29 23:04 lost+found
drwxr-xr-x.  2 root root  4096 Jun  1 16:14 media
drwxr-xr-x.  2 root root  4096 Jun  1 16:14 mnt
drwxr-xr-x.  2 root root  4096 Apr 29 23:04 oem
drwxr-xr-x.  4 root root  4096 Jun  1 16:14 opt
drwxr-xr-x.  2 root root  4096 Jun  1 16:14 proc
drwx------.  3 root root  4096 Jun  1 16:14 root
drwxr-xr-x.  3 root root  4096 Jun  1 16:14 run
lrwxrwxrwx.  1 root root     7 Jun  1 16:14 sbin -> usr/bin
drwxr-xr-x.  2 root root  4096 Jun  1 16:14 srv
drwxr-xr-x.  2 root root  4096 Jun  1 16:14 sys
drwxr-xr-x.  2 root root  4096 Jun  1 16:14 tmp
drwxr-xr-x.  2 root root  4096 Apr 29 23:04 usr
drwxr-xr-x. 10 root root  4096 Jun  1 16:14 var
```
Output of `ls -la /mnt/flatcar-data/home/`:

```bash
ls -la /mnt/flatcar-data/home/
total 12
drwxr-xr-x.  3 root root 4096 Jun  1 16:14 .
drwxr-xr-x. 20 root root 4096 Jun  1 16:14 ..
drwxr-xr-x.  3 core core 4096 Jun  1 16:14 core
```

Output of `ls -la /mnt/flatcar-data/home/core/`:

![Image](https://github.com/user-attachments/assets/9ba46323-bec8-4eaa-a149-9b140d3d2646)

Output of `ls -la /mnt/flatcar-data/home/core/.ssh/`:

```bash
total 20
drwx------. 4 core core 4096 Jun  1 16:14 .
drwxr-xr-x. 3 core core 4096 Jun  1 16:14 ..
drwxr-xr-x. 2 core core 4096 Jun  1 16:14 .authorized_keys.d.old
-rw-r--r--. 1 core core  134 Jun  1 16:14 authorized_keys
drwxr-xr-x. 2 core core 4096 Jun  1 16:14 authorized_keys.d
```

Output of `cat /mnt/flatcar-data/home/core/.ssh/authorized_keys`: 

```bash
# auto-generated by update-ssh-keys
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBci1xz1g+pS9xs+KA6ymADE4w5rlrf+AXiQSP/mE/uH flatcar-spacectl
```

Output of `ls -la /mnt/flatcar-data/home/core/.ssh/authorized_keys`:
(permissions look off here? 644 instead of 600 maybe that's the problem, did my ignition config somehow changed this permission?)

```bash
-rw-r--r--. 1 core core 134 Jun  1 16:14 /mnt/flatcar-data/home/core/.ssh/authorized_keys
```

Output of `ls -al /mnt/flatcar-data/home/core/.ssh/authorized_keys.d/`:

```bash
total 12
drwxr-xr-x. 2 core core 4096 Jun  1 16:14 .
drwx------. 4 core core 4096 Jun  1 16:14 ..
-rw-r--r--. 1 core core   98 Jun  1 16:14 ignition
```

Output of `cat /mnt/flatcar-data/home/core/.ssh/authorized_keys.d/ignition`:

```bash
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBci1xz1g+pS9xs+KA6ymADE4w5rlrf+AXiQSP/mE/uH flatcar-spacectl
```
Output of `ls -al /mnt/flatcar-data/home/core/.ssh/.authorized_keys.d.old/`:

```bash
total 8
drwxr-xr-x. 2 core core 4096 Jun  1 16:14 .
drwx------. 4 core core 4096 Jun  1 16:14 ..
```

Output of `sudo cat /mnt/flatcar-system/share/flatcar/etc/ssh/sshd_config | grep -E "(StrictModes|AuthorizedKeysFile)"`: 
(maybe this is the problem? I did not touch this in my ignition config)

```bash
#StrictModes yes
#AuthorizedKeysFile     .ssh/authorized_keys
```

> And how long after boot does the power outage have to be to cause issues.

If the power outage is even for couple of sec, say I had a power outage but the generator kicked in within 50sec I would see this issue. First I thought I did something wrong with my ignition config, but when I simulated a power outage by pulling the power cord and plugging it back after just few seconds, I still saw the same issue.

**Comment by reaper8055** [comment]
> This is weird - the authorized_keys file is generated and properly synced+renamed+synced for durability. https://github.com/flatcar/update-ssh-keys/blob/main/src/lib.rs#L348-L375

I went through the code and the code seems to be doing everything correctly. I was wondering if there's a different package/library where `sshd_config` and file permissions for `~/.ssh/authorized_keys` are configured? 

I am asking because I tried setting the file permissions myself in my `flatcar.yml` and simulated a power outage by pulling the power cord and this time ssh upon boot didn't fail and ssh worked flawlessly, here's the `flatcar.yml` I used:

```yaml
variant: flatcar
version: 1.0.0

passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBci1xz1g+pS9xs+KA6ymADE4w5rlrf+AXiQSP/mE/uH flatcar-spacectl'
      groups: [ sudo, docker ]

storage:
  files:
    - path: /etc/flatcar/update.conf
      overwrite: true
      mode: 0644
      contents:
        inline: |
          REBOOT_STRATEGY=best-effort

    - path: /etc/hostname
      mode: 0644
      contents:
        inline: athena.spacectl.arpa

    - path: /etc/sudoers.d/core
      mode: 0440
      contents:
        inline: |
          core ALL=(ALL) NOPASSWD: ALL

    # Explicitly create authorized_keys with correct permissions
    - path: /home/core/.ssh/authorized_keys
      mode: 0600
      user:
        name: core
      group:
        name: core
      contents:
        inline: |
          # auto-generated by ignition
          ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBci1xz1g+pS9xs+KA6ymADE4w5rlrf+AXiQSP/mE/uH flatcar-spacectl

    - path: /etc/systemd/network/10-enp2s0.network
      mode: 0644
      contents:
        inline: |
          [Match]
          Name=enp2s0

          [Network]
          DHCP=yes
    - path: /etc/systemd/network/10-enp3s0.network
      mode: 0644
      contents:
        inline: |
          [Match]
          Name=enp3s0

          [Network]
          DHCP=yes
    - path: /etc/systemd/network/10-enp4s0.network
      mode: 0644
      contents:
        inline: |
          [Match]
          Name=enp4s0

          [Network]
          DHCP=yes
    - path: /etc/systemd/network/10-enp5s0.network
      mode: 0644
      contents:
        inline: |
          [Match]
          Name=enp5s0

          [Network]
          DHCP=yes
    - path: /etc/systemd/network/10-enp6s0.network
      mode: 0644
      contents:
        inline: |
          [Match]
          Name=enp6s0

          [Network]
          DHCP=yes

systemd:
  units:
    - name: sshd.service
      enabled: true

    - name: systemd-networkd.service
      enabled: true

    - name: update-engine.service
      enabled: true

    - name: locksmithd.service
      enabled: true
      mask: false

    # Permission recovery service as additional protection
    - name: ssh-permission-fix.service
      enabled: true
      contents: |
        [Unit]
        Description=Ensure SSH authorized_keys has correct permissions
        After=multi-user.target
        Before=sshd.service

        [Service]
        Type=oneshot
        ExecStart=/bin/bash -c 'if [[ -f /home/core/.ssh/authorized_keys ]] && [[ $(stat -c %%a /home/core/.ssh/authorized_keys) != "600" ]]; then chmod 600 /home/core/.ssh/authorized_keys && chown core:core /home/core/.ssh/authorized_keys; fi'

        [Install]
        WantedBy=multi-user.target

```
