### ISSUE TITLE
Always enable BPF JIT with CONFIG_BPF_JIT_ALWAYS_ON=y

### ISSUE THREAD

**Issue by alban** [flatcar/Flatcar#185]
**Current situation**
Current Linux kernel options:
```
# CONFIG_BPF_JIT_ALWAYS_ON is not set
CONFIG_BPF_JIT=y
```
Current default setup:
```
$ cat /proc/sys/net/core/bpf_jit_enable
0
```

**Impact**
Using the eBPF interpreter instead of generating efficient JIT code has an impact on:
- performance
- security

See CONFIG_BPF_JIT_ALWAYS_ON documentation:
> Enables BPF JIT and removes BPF interpreter to avoid speculative execution of BPF instructions by the interpreter

**Ideal future situation**

- Better performance
- Better security

**Implementation options**
- CONFIG_BPF_JIT_ALWAYS_ON=y

**Additional information**

BPF JIT does not work on all architectures but work on x86_64 and arm64:
See [Cilium's BPF documentation](https://docs.cilium.io/en/v1.8/bpf/):
> Thus, it is also generally recommended for widely used JITs in case of main stream architectures such as x86_64 and arm64.

/cc @mauriciovasquezbernal

**Comment by alban** [comment]
Note: as a workaround, to enable BPF JIT manually:
```
$ sudo sysctl net/core/bpf_jit_enable=1
net.core.bpf_jit_enable = 1
```

**Comment by ipochi** [comment]
In Lokomotive, one can provide a clc snippet to enable `bpf_jit_enable` upon cluster deployment.

```
storage:
  files:
    - path: /etc/sysctl.d/bpf_jit_enable.conf
      filesystem: root
      contents:
        inline: net.core.bpf_jit_enable=1
      mode: 0644
```

https://github.com/kinvolk/lokomotive/blob/master/docs/concepts/flatcar-container-linux.md#customization
