### ISSUE TITLE
dependency failed for filesystem check on /dev/mapper/user after installing to disk

### ISSUE THREAD

**Issue by silencej** [flatcar/Flatcar#230]
## Description

Use matchbox to install flatcar 2605.7.0, then boot from disk, the error stops booting: dependency failed for filesystem check on /dev/mapper/user. WARN: /dev/disk/by-label/ROOT doesnot exist

## Details

The Matchbox configs are as follows:

### groups

groups/install.json

```json
{
  "id": "stage-0",
  "name": "Flatcar Linux install",
  "profile": "flatcar-install",
  "metadata": {
    "os_channel": "stable",
    "os_version": "2605.7.0",
    "ignition_endpoint": "http://192.177.1.1:8088/ignition",
    "baseurl": "http://192.177.1.1:8088/assets/flatcar"
  }
}
```

groups/flatcar.json

```json
{
  "id": "stage-1",
  "name": "Flatcar Linux",
  "profile": "flatcar",
  "selector": {
    "os": "installed"
  },
  "metadata": {
  }
}
```

### profiles

profiles/flatcar-install.json
```json
{
  "id": "flatcar-install",
  "name": "Flatcar Linux install to disk",
  "boot": {
    "kernel": "/assets/flatcar/2605.7.0/flatcar_production_pxe.vmlinuz",
    "initrd": [
      "/assets/flatcar/2605.7.0/flatcar_production_pxe_image.cpio.gz"
    ],
    "args": [
      "initrd=flatcar_production_pxe_image.cpio.gz",
      "flatcar.config.url=http://192.177.1.1:8088/ignition?uuid=${uuid}&mac=${mac:hexhyp}",
      "flatcar.first_boot=yes",
      "console=tty0",
      "console=ttyS0",
      "flatcar.autologin"
    ]
  },
  "ignition_id": "flatcar-install.yaml"
}
```

profiles/flatcar.json
```json
{
  "id": "flatcar",
  "name": "Flatcar Linux",
  "boot": {
    "kernel": "/assets/flatcar/2605.7.0/flatcar_production_pxe.vmlinuz",
    "initrd": [
      "/assets/flatcar/2605.7.0/flatcar_production_pxe_image.cpio.gz"
    ],
    "args": [
      "initrd=flatcar_production_pxe_image.cpio.gz",
      "flatcar.config.url=http://192.177.1.1:8088/ignition?uuid=${uuid}&mac=${mac:hexhyp}",
      "flatcar.first_boot=yes",
      "console=tty0",
      "console=ttyS0",
      "flatcar.autologin"
    ]
  },
  "ignition_id": "flatcar.yaml"
}
```

### ignitions

ignition/flatcar-install.yaml

```yaml
---
systemd:
  units:
    - name: installer.service
      enable: true
      contents: |
        [Unit]
        Requires=network-online.target
        After=network-online.target
        [Service]
        Type=simple
        ExecStart=/opt/installer
        [Install]
        WantedBy=multi-user.target
storage:
  files:
    - path: /opt/installer
      filesystem: root
      mode: 0500
      contents:
        inline: |
          #!/bin/bash -ex
          curl --retry 10 --fail "{{.ignition_endpoint}}?{{.request.raw_query}}&os=installed" -o ignition.json
          flatcar-install \
            -d /dev/sda \
            -C {{.os_channel}} \
            -V {{.os_version}} \
            {{- if index . "baseurl"}}-b {{.baseurl}} \{{end}}
            -i ignition.json
          udevadm settle
          systemctl reboot

passwd:
  users:
    - name: devops
      groups:
        - wheel
        - docker
      password_hash: "$6$eCz.."
      ssh_authorized_keys:
        - "ssh-rsa AAAA... me"
{{ if index . "ssh_authorized_keys" }}
        {{ range $element := .ssh_authorized_keys }}
        - {{$element}}
        {{end}}
{{end}}
```

ignition/flatcar.yaml

```yaml
---
passwd:
  users:
    - name: devops
      groups:
        - wheel
        - docker
      password_hash: "$6$eCz.."
      ssh_authorized_keys:
        - "ssh-rsa AAAA... me"
{{ if index . "ssh_authorized_keys" }}
        {{ range $element := .ssh_authorized_keys }}
        - {{$element}}
        {{end}}
{{end}}
```

A side note, it may be related to matchbox, but I can't find any place to raise issue, so I raise one here.
