### ISSUE TITLE
K8s 1.20 docker deprecation: simplify use of containerd for k8s

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#284]
**Current situation**
Kubernetes 1.20 deprecated docker use; docker is still supported but issues a deprecation warning; support will be dropped in a future release. While we ship a CRI compatible containerd which can be used by kubernetes with some effort, it's not straightforward and it does not work out of the box.

**Impact**
* users are required to entirely replace the systemd unit of containerd shipped with Flatcar Container Linux in order to make k8s use containerd directly.
* alternatively, users are forced to continue using docker which has ceased to be the recommended set-up by upstream k8s.

**Ideal future situation**
* Immediate mitigation: documentation / example configuration is available on how to provision / set up Flatcar with containerd supporting k8s directly.
* Mid-term resolution: update containerd service file (and possibly containerd components / dependencies) to make k8s on containerd work out of the box (also see #283)

**Implementation options**
- [x]  Provide docs and example config for setting up containerd correctly to support running without docker (here: https://github.com/kinvolk/flatcar-docs/tree/main/docs/container-runtimes)
- [x]  make k8s on containerd work out of the box

**Comment by invidian** [comment]
Following Ignition configuration can be used to prepare `containerd` to be used by `kubelet` on Flatcar Beta (2705.1.0):
```yaml
storage:
  files:
  - path: /etc/containerd/config.toml
    filesystem: root
    mode: 0600
    contents:
      inline: |
        # persistent data location
        root = "/var/lib/containerd"
        # runtime state information
        state = "/run/docker/libcontainerd/containerd"
        # set containerd as a subreaper on linux when it is not running as PID 1
        subreaper = true
        # set containerd's OOM score
        oom_score = -999
        # CRI plugin listens on a TCP port by default
        disabled_plugins = []

        # grpc configuration
        [grpc]
        address = "/run/docker/libcontainerd/docker-containerd.sock"
        # socket uid
        uid = 0
        # socket gid
        gid = 0

        [plugins.linux]
        # shim binary name/path
        shim = "containerd-shim"
        # runtime binary name/path
        runtime = "runc"
        # do not use a shim when starting containers, saves on memory but
        # live restore is not supported
        no_shim = false
        # display shim logs in the containerd daemon's log output
        shim_debug = true
systemd:
  units:
  - name: containerd.service
    enabled: true
    dropins:
    - name: 10-use-custom-config.conf
      contents: |
        [Service]
        Environment=CONTAINERD_CONFIG=/etc/containerd/config.toml
        ExecStart=
        ExecStart=/usr/bin/env PATH=$${TORCX_BINDIR}:$${PATH} $${TORCX_BINDIR}/containerd --config $${CONTAINERD_CONFIG}
```

Diff from base `containerd` config:
```diff
diff --git a/run/torcx/unpack/docker/usr/share/containerd/config.toml b/etc/containerd/config.toml
index 2b37f3c..54969bd 100644
--- a/run/torcx/unpack/docker/usr/share/containerd/config.toml
+++ b/etc/containerd/config.toml
@@ -7,7 +7,7 @@ subreaper = true
 # set containerd's OOM score
 oom_score = -999
 # CRI plugin listens on a TCP port by default
-disabled_plugins = ["cri"]
+disabled_plugins = []

 # grpc configuration
 [grpc]
```

This configuration keeps backward-compatibility with Docker.

To tell `kubelet` to use containerd, make sure `kubelet` process has access to following directories on host file system:
- `/run/docker/libcontainerd/`
- `/var/lib/containerd`

And that it has access to the following binaries on host file system and that they are included in PATH:
- `/run/torcx/unpack/docker/bin/containerd-shim-runc-v1`
- `/run/torcx/unpack/docker/bin/containerd-shim-runc-v2` (optional?)

Then, add the following flags to `kubelet`:
- `--container-runtime=remote`
- `--container-runtime-endpoint=unix:///run/docker/libcontainerd/docker-containerd.sock`

#

If you don't need Docker compatibility, containerd config override can be just an empty file to use all defaults from upstream.

Then, make sure `kubelet` has access to the following directories on host file system:
- `/run/containerd`
- `/var/lib/containerd`

And that it has access to the following binaries on host file system and that they are included in PATH:
- `/run/torcx/unpack/docker/bin/containerd-shim-runc-v1`
- `/run/torcx/unpack/docker/bin/containerd-shim-runc-v2` (optional?)

Then, add the following flags to `kubelet`:
- `--container-runtime=remote`
- `--container-runtime-endpoint=unix:///run/containerd/containerd.sock`
