### ISSUE TITLE
Upgrade Package Request: ignition

### ISSUE THREAD

**Issue by Cougar** [flatcar/Flatcar#326]
**Package name and purpose**  
ignition got many enhancements and fixes multiple bugs since 0.34.0 (dated back to Dec 21, 2019). Latest release from CoreOS is v2.9.0

Package upstream:
 - https://github.com/kinvolk/ignition/releases
 - https://github.com/coreos/ignition/releases

**Benefits of upgrading this package** 
One important fix was an ability to use [systemd instantiated services](https://github.com/coreos/ignition/pull/934), merged  to [v2.2.0
](https://github.com/coreos/ignition/releases/tag/v2.2.0)

For example, instead of using
```yaml
systemd:
  units:
    - name: systemd-networkd-wait-online@eno1.service
      enabled: true
    - name: systemd-networkd-wait-online@ens1f1.service
      enabled: true
```
such hack is needed right now:
```yaml
storage:
  files:
  - path: /etc/systemd/system-preset/50-instantiated.preset
    filesystem: root
    contents:
      inline: |
        enable systemd-networkd-wait-online@.service eno1 ens1f1
```

Btw, the `systemd-networkd-wait-online@.service` is a custom unit because `systemd-networkd-wait-online.service` does not wait for all interfaces to become configured - not sure why (`RequiredForOnline=yes` exists in network configuration).

**Additional information**  
When other base components like Linux kernel and Docker get frequent upgrades, ignition has been forgotten for a long time. As time passes the more complicated the upgrade could be. The same goes for systemd #301.

Or are there any other ideas for ignition roadmap by Kinvolk?
