### ISSUE TITLE
2905.2.0 docker containers don't start.

### ISSUE THREAD

**Issue by dibi-codes** [flatcar/Flatcar#457]
## Description

Cluster containers with securityContext don't start anymore: 

```
standard_init_linux.go:228: exec user process caused: operation not permitted
```

## Impact

All containers with a securityContext setting don't start as expected.

## Environment and steps to reproduce

1. **Set-up**: RKE Cluster with Flatcar 2905.2.0 nodes
2. **Task**: Update from previous release 2765.2.6
3. **Action(s)**:
  a. Update downloads and installs automatically
  b. Node reboots
4. **Error**: Containers won't start anymore.

## Expected behavior

Containers should start.

## Additional information

Imho this is related to the change:

> Docker: disabled SELinux support in the Docker daemon

**Comment by tormath1** [comment]
@dabeck hi and thanks for raising this issue!
Could you share the `securityContext` applied to your containers, in order to reproduce / investigate locally. :)

**Comment by dibi-codes** [comment]
Sure.

This for example is from linkerd sidecar-containers:
```
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsUser: 2102
```

And this is from coreDNS:

```
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - all
          readOnlyRootFilesystem: true
```

Both failed after the upgrade.

**Comment by tormath1** [comment]
@dabeck thanks a lot ! 

Could we assert that `docker` is not running with SELinux mode enabled ? 

```
$ docker info -f "{{json .}}" | jq ".SecurityOptions"
[
  "name=seccomp,profile=default"
]
```

I can reproduce the issue if Docker is started with SELinux support:

```
$ docker run --rm -ti --security-opt=no-new-privileges alpine sh -c "echo hello"
hello
...
$ docker info -f "{{json .}}" | jq ".SecurityOptions"
[
  "name=seccomp,profile=default",
  "name=selinux"
]
$ docker run --rm -ti --security-opt=no-new-privileges alpine sh -c "echo hello"
standard_init_linux.go:228: exec user process caused: operation not permitted
$ dmesg
...
[ 2725.925461] audit: type=1401 audit(1627565833.055:242): op=security_bounded_transition seresult=denied oldcontext=system_u:system_r:kernel_t:s0 newcontext=system_u:system_r:svirt_lxc_net_t:s0:c136,c177
```

**Comment by dibi-codes** [comment]
thank you. You are right. Our nodes report this one:

```
$ docker info -f "{{json .}}" | jq ".SecurityOptions"
[
  "name=seccomp,profile=default",
  "name=selinux"
]
```

unfortunately I'm not sure why this is enabled even on a fresh setup FlatCar node!
Do you have any advice? Our cloud-config (yes we're actually still using cloud-config) has the following config for docker:

```
#cloud-config
coreos:
  locksmith:
    window-start: "23:00" # reboot automatically between 01:00 and
    window-length: "2h"   # 01:00 + 2h = 03:00
    endpoint: "http://127.0.0.1:32379"
  update:
    reboot-strategy: "etcd-lock"
  units:
    - name: docker.service
      command: start
      enable: true
      drop-ins:
        - name: "20-registry-mirror.conf"
          content: |
            [Service]
            Environment=DOCKER_OPTS='--live-restore --registry-mirror=https://mirror.gcr.io --registry-mirror=https://internal-mirror-domain'
```
