### ISSUE TITLE
Unable to resize root partition using ignition

### ISSUE THREAD

**Issue by Cubxity** [flatcar/Flatcar#462]
## Description

I am trying to provision a Flatcar node using a custom Ignition config. I would like to shrink the root partition and create a new partition for CEPH, however it did not partition as expected.

## Impact

I am unable to create a dedicated partition for CEPH with Ignition config.

## Environment and steps to reproduce

**Ignition config:**
```yaml
storage:
  disks:
    - device: /dev/sda
      wipe_table: false
      partitions:
        - label: root
          number: 9
          size: 40960
        - label: storage
          number: 10
          size: 0
  filesystems:
    - name: root
      mount:
        device: /dev/disk/by-partlabel/root
        format: xfs
        label: ROOT
        wipe_filesystem: true
    - name: storage
      mount:
        device: /dev/disk/by-partlabel/storage
        format: xfs
        label: STORAGE
        wipe_filesystem: true
  files:
    - path: /etc/hostname
      filesystem: root
      mode: 420
      contents:
        inline: test
```

1. **Set-up**: Rescue Linux; Hetzner Cloud.
2. **Task**: Install Flatcar Container Linux
3. **Action(s)**:
  a. Execute flatcar-install with the transpiled configuration
  b. Reboot the VPS
  c. Enter the TTY and execute `sudo fdisk -l`

## Expected behavior

/dev/sda9 has the size of 40 GiB and /dev/sda10 fills up the rest of the disk.

## Actual behavior

The partitions are not provisioned as expected. /dev/sda9 fills up the rest of the disk and /dev/sda10 does not exist.
![image](https://user-images.githubusercontent.com/27609129/127733766-15aa278e-e26e-4de0-930e-e007ab669364.png)

**Comment by jepio** [comment]
Thanks for the report.

With this ignition config:
```yaml
storage:
  disks:
    - device: /dev/vda
      wipe_table: false
      partitions:
        - label: STORAGE
          number: 10
          start: 43GB
          size: 0
  filesystems:
    - name: root
      mount:
        device: /dev/disk/by-partlabel/ROOT
        format: xfs
        label: ROOT
        wipe_filesystem: true
    - name: storage
      mount:
        device: /dev/disk/by-partlabel/STORAGE
        format: xfs
        label: STORAGE
        wipe_filesystem: true
```

I get the correct partition config:
```
Disk /dev/vda: 258.5 GiB, 277551775744 bytes, 542093312 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 03D05245-7F4F-48C6-B7DA-962693AFA544

Device        Start       End   Sectors   Size Type
/dev/vda1      4096    266239    262144   128M EFI System
/dev/vda2    266240    270335      4096     2M BIOS boot
/dev/vda3    270336   2367487   2097152     1G unknown
/dev/vda4   2367488   4464639   2097152     1G unknown
/dev/vda6   4464640   4726783    262144   128M Linux filesystem
/dev/vda7   4726784   4857855    131072    64M unknown
/dev/vda9   4857856  90177535  85319680  40.7G unknown
/dev/vda10 90177536 542093278 451915743 215.5G Linux filesystem
```

Something is wrong in handling the spec for partition 9. If I add a fixed size entry for part 9 the log says:
```
Aug 02 09:26:04 localhost ignition[492]: disks: createPartitions: op(3): running sgdisk with options: [--pretend --delete=9 --new=9:4857856:+10240M --new=10:44032M:+0M --info=10 /run/ignition/dev_aliases/dev/vda]
Aug 02 09:26:04 localhost ignition[492]: disks: createPartitions: op(3): partition 9 found with correct specifications
Aug 02 09:26:04 localhost ignition[492]: disks: createPartitions: op(3): running sgdisk with options: [--new=10:44032M:+0M --change-name=10:STORAGE /run/ignition/dev_aliases/dev/vda] 
```

**Comment by jepio** [comment]
The workaround has been provided; this could be revisited after the ignition v3 upgrade, which potentially solves it.

**Comment by tormath1** [comment]
Hi @Cubxity this seems to be fixed with Ignition 3:
```yaml
# butane < config.yaml > config.json
variant: flatcar
version: 1.1.0
storage:
  disks:
    - device: /dev/vda
      partitions:
        - label: ROOT
          number: 9
          size_mib: 3000
          resize: true
        - label: STORAGE
          number: 10
          size_mib: 0
  filesystems:
    - device: /dev/disk/by-partlabel/ROOT
      format: xfs
      wipe_filesystem: true
      label: ROOT
    - device: /dev/disk/by-partlabel/STORAGE
      format: xfs
      wipe_filesystem: true
      label: STORAGE
      with_mount_unit: true
      path: /mnt
```

This gives:
```
core@localhost ~ $ lsblk -f
NAME    FSTYPE   FSVER LABEL      UUID                                 FSAVAIL FSUSE% MOUNTPOINTS
loop3   squashfs 4.0
loop4   squashfs 4.0
loop5   squashfs 4.0
sr0
vda
|-vda1  vfat     FAT32 EFI-SYSTEM 6835-57BC
|-vda2
|-vda3  btrfs                     7caef027-0915-4c01-a3d5-28eff70f7ebd
| `-usr btrfs                     7caef027-0915-4c01-a3d5-28eff70f7ebd  986.9M     0% /usr
|-vda4
|-vda6  btrfs          OEM        be856aed-e34b-4b7b-be8a-0716b27db212    123M     1% /oem
|-vda7
|-vda9  xfs            ROOT       ee5f4b8d-6993-452b-ba61-9aaced168f67    2.8G     4% /
`-vda10 xfs            STORAGE    83507260-8510-4658-92bc-2a86f2f16c72    3.1G     3% /mnt
```

By the way, I see you're using Hetzner, I hope you're happy with the official Hetzner images now: https://www.flatcar.org/docs/latest/installing/cloud/hetzner/
