### ISSUE TITLE
Not able to create user via Ignition

### ISSUE THREAD

**Issue by alpana17** [flatcar/Flatcar#468]
![image](https://user-images.githubusercontent.com/8611615/128008974-13d38c1b-af79-48ee-914d-b20116f11674.png)

I am trying this. And passing Ignition in user data while launching AWS EC2 instance
But, not able to ssh in the instance.

**Comment by till** [comment]
The shell is nologin, you won't be able to ssh into the instance.

**Comment by alpana17** [comment]
I am trying to login with core user

**Comment by jepio** [comment]
Are you passing in the ssh key via ignition?

**Comment by alpana17** [comment]
No no,
ssh key is being passed via AWS UI while launching the instance.

If I remove this user creation part from Ignition, it works fine.
Is this part correct?

**Comment by jepio** [comment]
Sorry, I'm not familiar with AWS yet - @pothos do the two methods of passing ssh keys interfere?

**Comment by alpana17** [comment]
Can we have a screen share session to see the issue?

**Comment by pothos** [comment]
I think you can't log in because the Ignition config is incorrect.

With the following passed as `./flatcar_production_qemu.sh -i ignition.json` it bootloops because the user creation fails.

```
{
  "ignition": {
    "config": {},
    "security": {
      "tls": {}
    },
    "timeouts": {},
    "version": "2.3.0"
  },
  "networkd": {},
  "passwd": {
    "groups": [
      {
        "gid": 396,
        "name": "splunk"
      }
    ],
    "users": [
      {
        "groups": [
          "splunk"
        ],
        "name": "splunk",
        "shell": "/sbin/nologin",
        "system": true,
        "uid": 396
      }
    ]
  }
}
```

I'll have a look which part is missing in the config.

**Comment by pothos** [comment]
The `groups` field is for secondary groups, you can use the `primary_group` field in CLC (`primaryGroup` in Ignition JSON) to specify the group:

```
passwd:
  groups:
    - name: splunk
      gid: 396
  users:
    - name: splunk
      uid: 396
      primary_group: splunk
      shell: /sbin/nologin
      system: true
```

**Comment by alpana17** [comment]
User is created
![image](https://user-images.githubusercontent.com/8611615/128487294-d2a692c2-cd5e-4ae8-a957-0d03ef3e3fca.png)

Group is also created
![image](https://user-images.githubusercontent.com/8611615/128487440-d3f2401e-e687-4ffc-926e-c0c79fa65d6e.png)

But I can not see user mentioned in group

**Comment by jepio** [comment]
The 4th field in the first picture shows the primary group id, and matches the id in the picture. You can check with `id`:
```bash
core@localhost ~ $ id splunk
uid=396(splunk) gid=396(splunk) groups=396(splunk)
```

**Comment by alpana17** [comment]
yes, but why user splunk is not there in groups list in /etc/group file?

**Comment by jepio** [comment]
Seem only users having the group as a secondary group show up in `/etc/group`. I assure you that the configuration is correct now.

Or try the following ignition config:
```yaml
passwd:
  groups:
    - name: splunk
      gid: 396
  users:
    - name: splunk
      uid: 396
      primary_group: splunk
      groups:
        - splunk
      shell: /sbin/nologin
      system: true
```

Then `/etc/group` looks the way you want.
