### ISSUE TITLE
Add kola test for using the OEM partition with Ignition

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#486]
## Current situation

The OEM partition is a bit special in Ignition configurations because it's shipped as part of the image but needs to be declared first in an Ignition filesystem creation entry to place files on it via Ignition. In this use case, the filesystem creation entry will reuse the existing filesystem when the specs fit but a mismatch would lead to a boot error - which caused troubles when we altered the OEM specs because we switched the filesystem and to resolve this we added a relaxation of the reuse logics in Ignition. These newly added changes allow to reuse the OEM filesystem even if the filesystem format mismatches. This works both when the user specifies the `OEM` label or leaves it out.
There are currently no tests for this behavior in kola.

## Impact

A future Ignition update can introduce the old behavior.

## Ideal future situation

We have a test that checks that the OEM partition gets reused correctly if it's specified with a mismatching filesystem format and no label.

## **Implementation options
Since the new filesystem is btrfs for the OEM partition, a test would specify ext4.

```
storage:
  filesystems:
     - name: oem
       mount:
         device: "/dev/disk/by-label/OEM"
         format: "ext4"
  files:
    - path: /reuse_works
      filesystem: oem
      mode: 0644
      contents:
        inline: |
          check that the filesystem label "OEM" is still there
```
