### ISSUE TITLE
[RFE] Provide RaspberryPi 4 images

### ISSUE THREAD

**Issue by jepio** [flatcar/Flatcar#502]
## Current situation

It is possible to boot current arm64 alpha images (2983.0.0) on RaspberryPi 4, but there are several manual steps needed to perform the setup and to gain SSH access to the board.

## Impact

It is hard for people to play around with Flatcar on a very popular platform.

## Ideal future situation

We provide pre-built images with raspberrypi specific configuration, and some nice beginner friendly documentation (not assuming too much Flatcar knowledge) to perform installation and bring-up.

## Implementation options

Some suggestions will follow in the next comments.

## Additional information

Flatcar requires on ARM requires UEFI and ACPI support. This is available for RPI4 at https://github.com/pftf/RPi4 but not for other PIs, or many other boards.

**Comment by jepio** [comment]
I have this working on my own RaspberryPi and here's a rough description of the steps required and my WIP state. There is an easy way to get it working and a nice way.

# The easy way
You need an SD card and a USB stick (min 8GB).

## SD card

1. Format the SD card with MSDOS partition table, and create a single FAT partition.
2. Mount the FAT partition and unpack the contents of https://github.com/pftf/RPi4/releases/download/v1.28/RPi4_UEFI_Firmware_v1.28.zip to it.
3. You may be able to use a newer release from https://github.com/pftf/RPi4/releases, but thing occasionally break. I tested with v1.29, there are reports of various problems with v1.30.

## USB

1. Insert an unformatted USB stick
2. Fetch https://github.com/kinvolk/init/blob/flatcar-master/bin/flatcar-install
3. Save the following as `config.yaml`
```
storage:
  filesystems:
    - name: "OEM"
      mount:
        device: "/dev/disk/by-label/OEM"
        format: "btrfs"
  files:
    - filesystem: "OEM"
      path: "/grub.cfg"
      mode: 0644
      append: true
      contents:
        inline: |
          set linux_console="console=ttyAMA0,115200n8 console=tty1"
          set linux_append="flatcar.autologin usbcore.autosuspend=-1"
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - <INSERT YOUR SSH PUBKEY HERE>
```
Fill in your ssh public key, and transpile the config using `ct <config.yaml >config.json`. (https://github.com/kinvolk/container-linux-config-transpiler). Here is the json version:
```
{
  "ignition": {
    "config": {},
    "security": {
      "tls": {}
    },
    "timeouts": {},
    "version": "2.3.0"
  },
  "networkd": {},
  "passwd": {
    "users": [
      {
        "name": "core",
        "sshAuthorizedKeys": [
          "<INSERT YOUR SSH PUBKEY HERE>"
        ]
      }
    ]
  },
  "storage": {
    "files": [
      {
        "filesystem": "OEM",
        "path": "/grub.cfg",
        "append": true,
        "contents": {
          "source": "data:,set%20linux_console%3D%22console%3DttyAMA0%2C115200n8%20console%3Dtty1%22%0Aset%20linux_append%3D%22flatcar.autologin%20usbcore.autosuspend%3D-1%22%0A",
          "verification": {}
        },
        "mode": 420
      }
    ],
    "filesystems": [
      {
        "mount": {
          "device": "/dev/disk/by-label/OEM",
          "format": "btrfs"
        },
        "name": "OEM"
      }
    ]
  },
  "systemd": {}
}
```
4. Identify your USB drive (might be `/dev/sdb`)
5. Run `sudo ./flatcar-install -o "" -i config.json -B arm64-usr -C alpha -d <USB drive>`

## Boot
Insert the USB drive and SD card into the RPI4 and power-it up. Here is where there are a couple of tricky points:
* on first boot the image only logs to the serial console, not HDMI, which requires a dedicated cable. Subsequent boots log on both consoles
* if you dont have a screen, you need to know what IP address your PI gets through some other method
* the default UEFI firmware is setup to only expose a max of 3GB RAM due to compatibility with *other* OSes. This can be changed in firmware setup (F1) but requires either a serial cable or HDMI+keyboard.
