### ISSUE TITLE
Etcd Fails to Start After Upgrading to 2983.2.0

### ISSUE THREAD

**Issue by Silvenga** [flatcar/Flatcar#547]
## Description

Etcd is failing to start after upgrading to `2983.2.0`.

## Impact

Etcd is a core component of many Flatcar deployments. When the Etcd cluster is degraded, Flatcar isn't happy. 

## Environment and steps to reproduce

Using the template:
```yaml
etcd:
  name: ${name}
  listen_client_urls: http://${blah_ip}:2379,http://127.0.0.1:2379
  listen_peer_urls: http://${blah_ip}:2380
  # Unused after cluster construction.
  advertise_client_urls: http://${blah_ip}:2379
  initial_advertise_peer_urls: http://${blah_ip}:2380
  initial_cluster: ${etcd_initial_cluster}
  initial_cluster_state: new
  initial_cluster_token: blah
```

Upgrade from `2905.2.4` (our base image that nodes are based on) to `2983.2.0`.

Note that etcd-member is failing due to:
```
{
    "level": "fatal",
    "ts": 1636652386.2531393,
    "caller": "flags/flag.go:85",
    "msg": "conflicting environment variable is shadowed by corresponding command-line flag (either unset environment variable or disable flag))",
    "environment-variable": "ETCD_NAME",
    "stacktrace": "go.etcd.io/etcd/pkg/v3/flags.verifyEnv\n\t/tmp/etcd-release-3.5.0/etcd/release/etcd/pkg/flags/flag.go:85\ngo.etcd.io/etcd/pkg/v3/flags.SetFlagsFromEnv\n\t/tmp/etcd-release-3.5.0/etcd/release/etcd/pkg/flags/flag.go:45\ngo.etcd.io/etcd/server/v3/etcdmain.(*config).configFromCmdLine\n\t/tmp/etcd-release-3.5.0/etcd/release/etcd/server/etcdmain/config.go:373\ngo.etcd.io/etcd/server/v3/etcdmain.(*config).parse\n\t/tmp/etcd-release-3.5.0/etcd/release/etcd/server/etcdmain/config.go:343\ngo.etcd.io/etcd/server/v3/etcdmain.startEtcdOrProxyV2\n\t/tmp/etcd-release-3.5.0/etcd/release/etcd/server/etcdmain/etcd.go:58\ngo.etcd.io/etcd/server/v3/etcdmain.Main\n\t/tmp/etcd-release-3.5.0/etcd/release/etcd/server/etcdmain/main.go:40\nmain.main\n\t/tmp/etcd-release-3.5.0/etcd/release/etcd/server/main.go:32\nruntime.main\n\t/home/remote/sbatsche/.gvm/gos/go1.16.3/src/runtime/proc.go:225"
}
```

It appears the dropin `20-clct-etcd-member.conf` sets the `--name` option, while `etcd-member.service` sets `ETCD_NAME`.

## Expected behavior

Etcd continues to operate.

**Comment by jepio** [comment]
Someone reported the same in matrix yesterday, @tormath1 was looking at a proper fix.

etcd started treating this as an error recently. For now you will need to remove the `name` setting in your config template.

**Comment by Silvenga** [comment]
Ah, yes, Just noticed the upgrade from `v3.3.25` to `v3.5.0`.

I've been looking at quick fixes, I don't think removing `name` is an option, since `etcd-member.service` uses the machine id for `ETCD_NAME` - which is from `/etc/machine-id`. To bootstrap (and other operations?), a stable, "known before deployment" value is needed.

I'm currently messing with how systemd handles drop-ins with duplicate environment pairs.

**Comment by Silvenga** [comment]
Leaving this here for future generations:
```yaml
units:
    - name: etcd-member.service
      enable: true
      dropins:
        - name: 90-overrides-etcd-member.conf
          contents: |
            [Service]
            Environment="ETCD_NAME=${name}"
etcd:
  # name: ${name}
  listen_client_urls: http://${blah_ip}:2379,http://127.0.0.1:2379
  listen_peer_urls: http://${blah_ip}:2380
  # Unused after cluster construction.
  advertise_client_urls: http://${blah_ip}:2379
  initial_advertise_peer_urls: http://${blah_ip}:2380
  initial_cluster: ${etcd_initial_cluster}
  initial_cluster_state: new
  initial_cluster_token: blah
```

**Comment by tormath1** [comment]
Hi @Silvenga, 

As @jepio mentioned - it's related to the `etcd` upgrade, in this commit: https://github.com/etcd-io/etcd/commit/748ab8c3989886c2145eea06703d2981a224024f `warning` becomes `fatal` error.

With this CLC:
```yml
etcd:
  name: ${name}
  listen_client_urls: http://${blah_ip}:2379,http://127.0.0.1:2379
  listen_peer_urls: http://${blah_ip}:2380
  # Unused after cluster construction.
  advertise_client_urls: http://${blah_ip}:2379
  initial_advertise_peer_urls: http://${blah_ip}:2380
  initial_cluster: ${etcd_initial_cluster}
  initial_cluster_state: new
  initial_cluster_token: blah
```

`name: ${name}` will be translated to `--name ${name}` which will conflict with the `ETCD_NAME` from https://github.com/flatcar-linux/coreos-overlay/blob/main/app-admin/etcd-wrapper/files/etcd-member.service#L19.

That's why you're having this error message:
> conflicting environment variable is shadowed by corresponding command-line flag (either unset environment variable or disable flag)).

If you want to boot `etcd` correctly, you might need to remove `name: ` from your CLC or edit the running instance to add a new dropin in order to clear the `ETCD_NAME` value:

```
$ sudo systemctl edit etcd-member.service
```

With the following content:
```
[Service]
Environment="ETCD_NAME="
```

Then restart the service.
