### ISSUE TITLE
Afterburn documented steps do not work

### ISSUE THREAD

**Issue by aw1cks** [flatcar/Flatcar#573]
Following [this documentation](https://www.flatcar-linux.org/docs/latest/provisioning/config-transpiler/dynamic-data/), I am unable to get Afterburn to run as intended (for a custom platform). The service appears to not run at all  - there is no unit file for it.

Hostname is not being set - my instance is spun up as `localhost`.

This is running in Oracle Cloud, on an ARM instance, using the latest Beta ARM64 release.
The instance is spun up with the following ignition config:

```shell
localhost ~ # cat /usr/share/oem/grub.cfg
# Flatcar GRUB settings

set oem_id="qemu"
set linux_append="flatcar.autologin ignition.config.url=http://169.254.169.254/opc/v1/instance/metadata/ignition"
localhost ~ # awk '{print $13}' /proc/cmdline
ignition.config.url=http://169.254.169.254/opc/v1/instance/metadata/ignition
localhost ~ # curl -sL http://169.254.169.254/opc/v1/instance/metadata/ignition | jq
{
  "ignition": {
    "version": "2.3.0"
  },
  "passwd": {
    "users": [
      {
        "name": "core",
        "sshAuthorizedKeys": [
          "< my key >"
        ]
      }
    ]
  },
  "storage": {
    "files": [
      {
        "contents": {
          "source": "http://169.254.169.254/opc/v1/instance/metadata/afterburn"
        },
        "filesystem": "root",
        "mode": 493,
        "path": "/opt/get-metadata.sh"
      },
      {
        "contents": {
          "source": "data:,fs.inotify.max_user_watches%3D16184%0A"
        },
        "filesystem": "root",
        "mode": 420,
        "path": "/etc/sysctl.d/max-user-watches.conf"
      }
    ]
  },
  "systemd": {
    "units": [
      {
        "enabled": true,
        "name": "docker.service"
      },
      {
        "mask": true,
        "name": "locksmithd.service"
      },
      {
        "dropins": [
          {
            "contents": "[Service]\n# Empty ExecStart= prevents the previously defined ExecStart from running\nExecStart=\nExecStart=/opt/get-metadata.sh\n",
            "name": "use-script.conf"
          }
        ],
        "enabled": true,
        "name": "coreos-metadata.service"
      }
    ]
  }
}
localhost ~ #
```

The file is definitely written to `/opt/get-metadata.sh` correctly:

```shell
localhost ~ # cat /opt/get-metadata.sh
#!/bin/sh

set -e
set -x

hostname="COREOS_CUSTOM_HOSTNAME=$(curl -sL 'http://169.254.169.254/opc/v1/instance/' | jq -r '.displayName' | sed 's/_/-/g')"
ipv4_private="COREOS_CUSTOM_PRIVATE_IPV4=$(curl -sL 'http://169.254.169.254/opc/v1/vnics' | jq -r '.[].privateIp')"
ipv4_public="COREOS_CUSTOM_PUBLIC_IPV4=$(curl -sL 'https://ipinfo.io/ip')"

printf '%s\n%s\n%s\n' \
  "${hostname}" \
  "${ipv4_private}" \
  "${ipv4_public}" \
> /run/metadata/coreos
localhost ~ #
```

However, the hostname is not set, and the environment file is not written (but gets written fine when I execute the script manually):

```shell
localhost ~ # hostnamectl
   Static hostname: n/a
Transient hostname: localhost
         Icon name: computer-vm
           Chassis: vm
        Machine ID: d67c147477bb42a5bb237b6679ebe482
           Boot ID: 31edb3a130a7432ba8aa32134ef4f3bc
    Virtualization: kvm
  Operating System: Flatcar Container Linux by Kinvolk 3033.1.1 (Oklo)
            Kernel: Linux 5.10.80-flatcar
      Architecture: arm64
   Hardware Vendor: QEMU
    Hardware Model: KVM Virtual Machine
localhost ~ # cat /run/metadata/coreos
cat: /run/metadata/coreos: No such file or directory
localhost ~ # /opt/get-metadata.sh
++ curl -sL http://169.254.169.254/opc/v1/instance/
++ sed s/_/-/g
++ jq -r .displayName
+ hostname=COREOS_CUSTOM_HOSTNAME=inst-ftak8-flatcar-workers
++ curl -sL http://169.254.169.254/opc/v1/vnics
++ jq -r '.[].privateIp'
+ ipv4_private=COREOS_CUSTOM_PRIVATE_IPV4=10.144.3.193
++ curl -sL https://ipinfo.io/ip
+ ipv4_public=COREOS_CUSTOM_PUBLIC_IPV4=132.226.209.110
+ printf '%s\n%s\n%s\n' COREOS_CUSTOM_HOSTNAME=inst-ftak8-flatcar-workers COREOS_CUSTOM_PRIVATE_IPV4=10.144.3.193 COREOS_CUSTOM_PUBLIC_IPV4=132.226.209.110
localhost ~ # cat /run/metadata/coreos
COREOS_CUSTOM_HOSTNAME=inst-ftak8-flatcar-workers
COREOS_CUSTOM_PRIVATE_IPV4=10.144.3.193
COREOS_CUSTOM_PUBLIC_IPV4=132.226.209.110
localhost ~ #
```

The systemd service for coreos-metadata is not present (but the dropin file is):

```shell
localhost ~ # ls -l /run/systemd/system/
total 12
-rw-r--r--. 1 root root  865 Dec 11 16:56 containerd.service
-rw-r--r--. 1 root root 1635 Dec 11 16:56 docker.service
-rw-r--r--. 1 root root  239 Dec 11 16:56 docker.socket
drwxr-xr-x. 2 root root   60 Dec 11 16:56 sockets.target.wants
localhost ~ # cat /etc/systemd/system/coreos-metadata.service.d/use-script.conf
[Service]
# Empty ExecStart= prevents the previously defined ExecStart from running
ExecStart=
ExecStart=/opt/get-metadata.sh
localhost ~ #
```

I'm not sure if this is inaccurate documentation, or an actual bug.

To clarify, I am passing the platform to `ct`. I am using a Terraform provider to do this and my code looks like this:

```hcl
data "ct_config" "worker_ignition" {
  count    = var.worker_count_max
  content  = data.template_file.worker_config.*.rendered[count.index]
  strict   = true
  snippets = var.controlplane_ignition_snippets
  platform = "custom"
}
```

But I've confirmed that the output JSON is identical when running `ct -platform custom -in-file <my file>` too.

Here is the original YAML file for reference:

```yaml
---
storage:
  files:
    - path: /opt/get-metadata.sh
      filesystem: root
      mode: 0755
      contents:
        remote:
          url: http://169.254.169.254/opc/v1/instance/metadata/afterburn
    - path: /etc/sysctl.d/max-user-watches.conf
      filesystem: root
      mode: 0644
      contents:
        inline: |
          fs.inotify.max_user_watches=16184

passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - "< my key >"

systemd:
  units:
    - name: docker.service
      enabled: true
    - name: locksmithd.service
      mask: true
    - name: coreos-metadata.service
      enabled: true
      dropins:
       - name: use-script.conf
         contents: |
           [Service]
           # Empty ExecStart= prevents the previously defined ExecStart from running
           ExecStart=
           ExecStart=/opt/get-metadata.sh
```
