### ISSUE TITLE
kola: ease test writing

### ISSUE THREAD

**Issue by tormath1** [flatcar/Flatcar#655]
The goal of the issue is to propose a new layer on top of Kola to add tests. Most of the time, simple unit tests need the following elements:
- user-data for initial provisioning
- an input (the actual test to run)
- an expected output (the result of the input command)

Tests could be defined in `yaml` format and using `yaml` Go bindings and code generation we could generate the tests. With this approach, the current way to define tests will still be available.

Example the following [test](https://github.com/flatcar-linux/mantle/blob/1dba55fb41c29b46360f2e1280a1a59378de4284/kola/tests/ignition/sethostname.go#L102-L110):
```go
func setHostname(c cluster.TestCluster) {
	m := c.Machines()[0]


	out := c.MustSSH(m, "hostnamectl")


	if !strings.Contains(string(out), "Static hostname: core1") {
		c.Fatalf("hostname wasn't set correctly:\n%s", out)
	}
}
```

would be defined as follow:
```yml
---
- name: "Set hostname"
  input: "hostnamectl"
  output: "Static hostname: core1"
  clc: |-
    storage:
      files:
        - path: /etc/hostname
          filesystem: root
          contents:
            inline: core1
          mode: 0420
```
