### ISSUE TITLE
dev: Ignition 3 translation to strict when checking links

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#666]
## Description

`CheckPathUsesLink` in `ign-converter` is matches by prefix which is too simple

## Impact

The following Ignition 2.3.0 config (here CLC YAML) fails:
```
storage:
  files:
    - path: /helloworld
  links:
    - path: /hello
      target: /helloworld
```

## Expected behavior

It is accepted

## Additional information

This is `UsesOwnLinkError`: `%s uses link defined in config %q. Please use a link not defined in Storage:Links …`, it already happens in `files:` as `/helloworld uses link defined in config "/hello"` but actually it does not use a link at all (this was meant for directories, by the way and should not use a prefix but match by `/` as final character I think, so a solution would be to append `/` to the link path before matching the prefix).
