### ISSUE TITLE
Make /usr/lib an own directory

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#674]
## Current situation

Flatcar amd64 uses a symlink `/usr/lib` → `lib64` and stores all files in `/usr/lib64`.
Flatcar arm64 the symlink is not used and both are separate folders.

## Impact

Systemd-sysext amd64 images can't be mounted when they use a `/usr/lib` folder (as required in the spec)

Currently there is a workaround for that by following the same setup in the sysext image, e.g., here a CLC:

```
systemd:
  units:
    - name: systemd-sysext.service
      enabled: true
storage:
  files:
    - path: /etc/extensions/test/usr/lib64/extension-release.d/extension-release.test
      contents:
        inline: |
          ID=flatcar
          SYSEXT_LEVEL=1.0
    - path: /etc/extensions/test/usr/hello-sysext
      contents:
        inline: |
          sysext works
  links:
    - path: /etc/extensions/test/usr/lib
      target: lib64
```

## Ideal future situation

Two folders like on arm64

## Implementation options

A portage profile [update](https://www.gentoo.org/support/news-items/2019-06-05-amd64-17-1-profiles-are-now-stable.html) would bring this change (@krnowak)
