### ISSUE TITLE
New Package Request: docker compose

### ISSUE THREAD

**Issue by jepio** [flatcar/Flatcar#894]
**Package name and purpose**
Either include docker compose in flatcar, or provide documentation on how to easily enable it through ignition. 

- Package upstream repo: https://github.com/docker/compose
- Gentoo ebuild: https://github.com/gentoo/gentoo/blob/master/app-containers/docker-compose/docker-compose-2.11.2.ebuild

**Impact of adding this package to the Flatcar OS image**

The package improves on the following core values:
  - [ ] Secure by default
  - [ ] Always up to date
  - [x] Improve container experience
  - [x] Operate at scale / automation / telemetry

The package will increase the image size by: needs to be evaluated.

How might this package increase the attack surface:
- cli utility

**Benefits of adding this package**
docker compose (or docker-compose) is a simple container orchestration system.

**Additional information**
[ Please add any information that does not fit into any of the above sections here ]

**Comment by bignay2000** [comment]
I agree, this would be great to have docker-compose built-in.  It's literally the only thing I add to the OS.


Note that I install it after the system is online, you just have to use the writable /opt/bin location.  Be sure to run as root (sudo has issues)
___________________

sudo -i

curl -SL https://github.com/docker/compose/releases/download/v2.11.2/docker-compose-linux-x86_64 -o /opt/bin/docker-compose

chmod +x /opt/bin/docker-compose

**Comment by till** [comment]
I would really like to have this in the base. :)

**Comment by tormath1** [comment]
For the record, here's a Butane configuration to download `docker-compose` and run a simple application:
```yml
---
variant: flatcar
version: 1.0.0
storage:
  files:
    - path: /opt/bin/docker-compose
      contents:
        source: https://github.com/docker/compose/releases/download/v2.11.2/docker-compose-linux-x86_64
        verification:
          hash: sha512-8ad55ea1234e206ecad3e8ecf30f93de5cc764a423bf8ff179b25320f148e475b569ab9ec68d90eacfe97269528ff8fef1746c05381c7d05edc85d2f2c245e69
      mode: 0755
    - path: /home/core/docker-compose.yml
      contents:
        inline: |
          services:
            web:
              image: nginx
              ports:
                - 80:80
      mode: 0644
      user:
        name: core
      group:
        name: core
systemd:
  units:
    - name: application.service
      enabled: true
      contents: |
        [Unit]
        Description=Minimalist docker-compose example
        [Service]
        ExecStart=/opt/bin/docker-compose -f /home/core/docker-compose.yml up
        [Install]
        WantedBy=multi-user.target
``` 

To generate Ignition:
```
podman run --rm -i quay.io/coreos/butane:latest < config.yaml > config.json
```
