### ISSUE TITLE
[RFE] update nftables and ship systemd unit

### ISSUE THREAD

**Issue by jepio** [flatcar/Flatcar#900]
## Current situation

We currently ship nftables-0.9.9 and no systemd unit to automatically apply rules at boot.
Gentoo has nftables-1.0.5

## Impact

Harder than necessary to enable nftables during boot.

## Ideal future situation

nftables systemd unit part of flatcar image.

## Implementation options

Update nftables ebuild in coreos-overlay (while checking which downstream changes are still necessary).

**Comment by pothos** [comment]
Thanks. The systemd unit topic is interesting, I guess we could try to be close to the workflow we have for iptables config files and the [Gentoo systemd unit](https://gitweb.gentoo.org/repo/gentoo.git/tree/net-firewall/nftables/files/systemd/nftables-restore.service) looks like it fits well - if Flatcar follows the Gentoo way we could redirect to the Gentoo docs instead of writing our own docs.

Just for reference, a very different way of configuring nftables can be found on Fedora:
```
[Unit]
Description=Netfilter Tables
Documentation=man:nft(8)
Wants=network-pre.target
Before=network-pre.target

[Service]
Type=oneshot
ProtectSystem=full
ProtectHome=true
ExecStart=/sbin/nft -f /etc/sysconfig/nftables.conf
ExecReload=/sbin/nft 'flush ruleset; include "/etc/sysconfig/nftables.conf";'
ExecStop=/sbin/nft flush ruleset
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
```
The `/etc/sysconfig/` file includes `/etc/nftables/main.nft` and both the service and the inclusion of the `main.nft` are disabled by default on my machine.

**Comment by bexelbie** [comment]
Is this still being considered?

**Comment by tormath1** [comment]
> Is this still being considered?

Flatcar next alpha will ship nftables-1.1.1 but we are masking the shipped units:
https://github.com/flatcar/scripts/blob/c9c1f6f4376dac6337c0576534d557eae305511f/sdk_container/src/third_party/coreos-overlay/coreos/config/env/net-firewall/nftables#L1

_checking with the team why we're masking those files_

**Comment by tormath1** [comment]
> Is this still being considered?

@bexelbie thanks for the heads-up. `nftables-load` and `nftables-store` services should be available in the next Alpha and you can store your nftables rules into `/var/lib/nftables/rules-save`. Here's an example:
```yaml
variant: flatcar
version: 1.0.0
storage:
  files:
    - path: /var/lib/nftables/rules-save
      mode: 0644
      contents:
        inline: |
          table ip filter {
          	chain INPUT {
          		type filter hook input priority filter; policy accept;
          		tcp dport 80 counter packets 0 bytes 0 drop
          	}
          }
systemd:
 units:
   - name: nftables-load.service
     enabled: true
```
