### ISSUE TITLE
Ignition fails to detect cloud-config when jinja templates are used

### ISSUE THREAD

**Issue by hrak** [flatcar/Flatcar#953]
## Description

Ignition's `isCloudConfig` function doesn't properly detect cloud-config when using [jinja templates](https://cloudinit.readthedocs.io/en/stable/topics/instancedata.html#using-instance-data). For example, Kubernetes cluster-api [uses jinja templates for cloud-config](https://github.com/kubernetes-sigs/cluster-api/blob/5c6fb4bc89efb6325852392e8369ba6aa767881b/bootstrap/kubeadm/internal/cloudinit/cloudinit.go#L38). The user-data fetched from metadata service looks like this (gzipped):

```yaml
## template: jinja
#cloud-config

write_files:
-   path: /etc/kubernetes/pki/ca.crt
    owner: root:root
    permissions: '0640'
    content: |
      -----BEGIN CERTIFICATE-----
      <snip snip>
      -----END CERTIFICATE-----
      etc. etc.
```

The [`isCloudConfig`](https://github.com/flatcar/ignition/blob/6d8ad3f39728bcab4b982e21594043bf3bb52d2b/config/v2_4/cloudinit.go#L27) function only looks for the first line of the config to contain `#cloud-config`:

```go
func isCloudConfig(userdata []byte) bool {
	header := strings.SplitN(string(decompressIfGzipped(userdata)), "\n", 2)[0]

	// Trim trailing whitespaces
	header = strings.TrimRightFunc(header, unicode.IsSpace)

	return (header == "#cloud-config")
}
```

But in the case of Jinja templates, the first header is `## template: jinja`. The function `isCloudConfig` will have to be adapted to check in at least the first 2 lines for `#cloud-config`.

## Impact

cloud-config is not detected, resulting in `config.Parse` attempting to handle the user-data as raw json, which it isn't (its gzipped yaml), resulting in a boot failure and emergency mode

![Screenshot 2023-01-26 at 13 45 43](https://user-images.githubusercontent.com/1963283/215047084-3f28c12b-f601-4a36-8c48-680a4b603279.png)

## Environment and steps to reproduce

1. **Set-up**:
flatcar-stable-3374.2.3 running in Cloudstack (KVM virt)
2. **Task**: booting a control plane node using [Kubernetes cluster-api](https://github.com/kubernetes-sigs/cluster-api)
3. **Action(s)**: 
  a. boot an instance with user-data containing a cloud-config using jinja templates
4. **Error**: see above

## Expected behavior

Proper boot and processing of cloud-config

## Additional information

Please add any information here that does not fit the above format.
