### ISSUE TITLE
Ignition: Can't specify the OEM partition path for use in the initrd

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#979]
## Description

The following Butane config was converted from CLC where it worked because ign-converter uses a temporary `path:` for the initrd mount point but here we directly use `/usr/share/oem` which already exists as mount point in the initrd:

```
variant: flatcar
version: 1.0.0
storage:
  files:
    - path: /usr/share/oem/script
      mode: 0755
      contents:
        inline: |
          #!/bin/bash
          set -euo pipefail
  filesystems:
    - device: /dev/disk/by-label/OEM
      path: /usr/share/oem
      format: btrfs
      label: OEM
```

## Impact

Boot failure, depending on whether the OEM part is mounted in the initrd or not

## Environment and steps to reproduce

1. **Set-up**: run `butane` to convert to ignition
2. **Task**: boot Flatcar with the qemu script and this ignition file
3. **Action(s)**: `sudo touch /boot/flatcar/first_boot && sudo reboot`
4. **Error**: `vda6 already mounted on /sysroot/usr/share/oem`

## Expected behavior

Ignition reuses the mount point (and doesn't unmount it later either), or Ignition uses a temporary mount point instead.
