### ISSUE TITLE
[RFE] Send the logs to a remote target using a kernel parameter

### ISSUE THREAD

**Issue by mgrzybek** [flatcar/Flatcar#990]
## Current situation

Some parameters can be added to the boot sequence, especially while using the iPXE installation method. In case of crash, the logs are only stored locally and are available using a local console or SSH.

## Impact

The administrator has to connect against the in-memory Flatcar Linux running on the target machine so as to see the logs.

## Ideal future situation

A kernel parameter such as `flatcar.remote_logs_url=http://target.com:80` should be used to send log messages to a remote target.

`ignition` can be configured to get `systemd-journal-upload.service` up and running. An article could be written in the documentation.

## Implementation options

`systemd-journal-upload.service` could be used but only supports HTTP (https://www.freedesktop.org/software/systemd/man/systemd-journal-upload.service.html#).

## Additional information

N.A.

**Comment by pothos** [comment]
Thanks, yes, we need a docs section for that.
So, it roughly works like that, on one machine you start `systemd-journal-gatewayd.socket` and then the collecting machine should be able to get it with `sudo systemd-run --unit systemd-journal-remote-client /usr/lib/systemd/systemd-journal-remote --url http://IPADDR:19531`.
Reading entries can be done by filtering for the hostname `sudo journalctl _HOSTNAME=gateway -t core --file /var/log/journal/remote/remote-IPADDR.journal`.
Now that is just the one-time action I copied from our test suite and not a persistent setup nor in any way secured.
I'm sure that there are other ways, I also didn't read the upstream docs. You can also run rsyslog by forwarding the journal to syslog.

**Comment by tormath1** [comment]
Hi @mgrzybek,

What about this configuration:
```yaml
# butane < config.yaml > config.json
variant: flatcar
version: 1.0.0
systemd:
  units:
    - name: systemd-journal-upload.service
      enabled: true
storage:
  files:
    - path: /etc/systemd/journal-upload.conf
      overwrite: true
      contents:
        inline: |
          [Upload]
          URL=http://target.com:80
```

it's not enough for your needs ?
